-- ============================================================
-- TNTET Personal Coach - Sample Question Import
-- Generated: 2026-08-28T12:38:00.863Z
-- 100 questions across 6 papers
-- Run in the Supabase SQL Editor (public schema).
-- ============================================================

-- 1) question_papers (upsert by id)
INSERT INTO public.question_papers (id, year, paper_type, shift, source, total_questions) VALUES
  ('smp_2022_PAPER_I', 2022, 'PAPER_I', NULL, 'TRB TNTET Sample', 32),
  ('smp_2019_PAPER_I', 2019, 'PAPER_I', NULL, 'TRB TNTET Sample', 30),
  ('smp_2022_PAPER_II_MATH_SCI', 2022, 'PAPER_II_MATH_SCI', NULL, 'TRB TNTET Sample', 12),
  ('smp_2019_PAPER_II_MATH_SCI', 2019, 'PAPER_II_MATH_SCI', NULL, 'TRB TNTET Sample', 12),
  ('smp_2022_PAPER_II_SOC_SCI', 2022, 'PAPER_II_SOC_SCI', NULL, 'TRB TNTET Sample', 7),
  ('smp_2019_PAPER_II_SOC_SCI', 2019, 'PAPER_II_SOC_SCI', NULL, 'TRB TNTET Sample', 7)
ON CONFLICT (id) DO UPDATE SET year = EXCLUDED.year, paper_type = EXCLUDED.paper_type, total_questions = EXCLUDED.total_questions;

-- 2) questions (upsert by id)
INSERT INTO public.questions (
  id, paper_id, subject_id, topic_id, sno, question_no,
  question_en, question_ta,
  option_a_en, option_a_ta, option_b_en, option_b_ta,
  option_c_en, option_c_ta, option_d_en, option_d_ta,
  correct_option, difficulty, question_type,
  explanation_en, explanation_ta,
  concept_summary_en, concept_summary_ta, syllabus_ref,
  year, is_active
) VALUES
  (
    'q_sample_001',
    'smp_2022_PAPER_I',
    'cdp',
    'cdp_physical_growth',
    1,
    '12',
    'According to Piaget, which stage of cognitive development do children in the 2–7 age range typically reach?',
    'பியாஜே கூற்றுப்படி, 2–7 வயதுடைய குழந்தைகள் பொதுவாக எந்த அறிவாற்றல் வளர்ச்சி நிலையை அடைகின்றனர்?',
    'Sensory-motor stage', 'உணர்வு-மோட்டார் நிலை',
    'Pre-operational stage', 'முன்-செயல் நிலை',
    'Concrete operational stage', 'குறிப்பிட்ட செயல் நிலை',
    'Formal operational stage', 'முறைசார் செயல் நிலை',
    1,
    'easy',
    'factual',
    'Children aged 2–7 are in the pre-operational stage, where symbolic thinking and language develop but logical reasoning is limited.',
    '2–7 வயதுடைய குழந்தைகள் முன்-செயல் நிலையில் உள்ளனர், அங்கு குறியீட்டு சிந்தனை மற்றும் மொழி வளரும், ஆனால் தர்க்கரீதியான பகுத்தறிவு குறைவாக இருக்கும்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_002',
    'smp_2019_PAPER_I',
    'cdp',
    'cdp_learning_types',
    2,
    '8',
    'Which of the following is an example of signal learning in Gagné''s hierarchy of learning?',
    'கனேயின் கற்றல் படிநிலையில் பின்வருவனவற்றுள் எது சிக்னல் கற்றலுக்கு example?',
    'Ringing a bell before feeding a dog', 'நாய்க்கு உணவு கொடுப்பதற்கு முன் மணி ஓசை',
    'Solving a maths word problem', 'கணிதச் சிக்கலைத் தீர்ப்பது',
    'Memorizing a poem', 'கவிதையை மனப்பாடம் செய்வது',
    'Drawing a picture of a tree', 'மரத்தின் படத்தை வரைவது',
    0,
    'easy',
    'conceptual',
    'Signal learning, the simplest level in Gagné''s hierarchy, is a conditioned (Pavlovian) response to a stimulus such as a bell or a warning.',
    'கனேயின் படிநிலையில் எளிமையான நிலையான சிக்னல் கற்றல், மணி அல்லது எச்சரிக்கை போன்ற தூண்டுதலுக்கான (பாவ்லோவிய) நிபந்தனைப் பதில்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_003',
    'smp_2022_PAPER_I',
    'cdp',
    'cdp_inclusive',
    3,
    '27',
    'In an inclusive classroom, the most appropriate first step for a teacher noticing a student with a suspected specific learning disability is to:',
    'உள்ளடக்கிய வகுப்பறையில், குறிப்பிட்ட கற்றல் குறைபாடு இருப்பதாகக் கருதப்படும் மாணவரைக் கவனிக்கும் ஆசிரியர் எடுக்க வேண்டிய மிகச் சரியான முதல் படி:',
    'Refer the child for assessment and adapt teaching', 'குழந்தையை மதிப்பீட்டுக்கு அனுப்பி கற்பித்தலை மாற்றியமைத்தல்',
    'Ignore the difficulty to avoid embarrassment', 'சங்கடத்தைத் தவிர்க்க கஷ்டத்தை புறக்கணித்தல்',
    'Move the child to a lower class', 'குழந்தையை குறைந்த வகுப்புக்கு மாற்றுதல்',
    'Discipline the child for not studying', 'படிக்காததற்காக குழந்தையை தண்டித்தல்',
    0,
    'medium',
    'pedagogy',
    'An inclusive teacher first responds to concerns by seeking formal assessment and then adapting instruction to meet the child''s needs.',
    'உள்ளடக்கிய ஆசிரியர் முதலில் முறையான மதிப்பீட்டை நாடி, பின்னர் குழந்தையின் தேவைகளுக்கேற்ப கற்பித்தலை மாற்றியமைக்கிறார்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_004',
    'smp_2019_PAPER_I',
    'cdp',
    'cdp_constructivist',
    4,
    '35',
    'A constructivist teacher would most likely encourage students to:',
    'கட்டமைப்பாளர் ஆசிரியர் மாணவர்களை எதைச் செய்ய ஊக்குவிப்பார்?',
    'Build knowledge through hands-on experience and reflection', 'கைகளால் செய்யும் அனுபவம் மற்றும் பிரதிபலிப்பு மூலம் அறிவை உருவாக்குதல்',
    'Only memorize textbook answers', 'பாடப்புத்தக பதில்களை மட்டும் மனப்பாடம் செய்தல்',
    'Listen to long lectures passively', 'நீண்ட விரிவுரைகளை செயலற்று கேட்டல்',
    'Copy notes from the blackboard', 'பலகையிலிருந்து குறிப்புகளை நகலெடுத்தல்',
    0,
    'easy',
    'pedagogy',
    'Constructivism holds that learners actively build understanding through experience, discovery, and reflection rather than passive reception.',
    'கட்டமைப்பியல் கற்றவர்கள் செயலற்ற பெறுதல் அல்லாமல் அனுபவம், கண்டுபிடிப்பு மற்றும் பிரதிபலிப்பு மூலம் அறிவைத் தீவிரமாக உருவாக்குகின்றனர் என்று கூறுகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_005',
    'smp_2022_PAPER_I',
    'cdp',
    'cdp_evaluation',
    5,
    '44',
    'Continuous and Comprehensive Evaluation (CCE) in formative assessment primarily aims to:',
    'தொடர்ச்சியான மற்றும் விரிவான மதிப்பீடு (CCE) வடிவான மதிப்பீட்டில் முதன்மையாக எதை இலக்காகக் கொண்டுள்ளது?',
    'Provide ongoing feedback to improve learning', 'கற்றலை மேம்படுத்த தொடர்ச்சியான கருத்தை வழங்குதல்',
    'Rank students in a single final exam', 'ஒரே இறுதித் தேர்வில் மாணவர்களை தரவரிசைப்படுத்துதல்',
    'Award marks for attendance only', 'வருகைக்கு மட்டும் மதிப்பெண் வழங்குதல்',
    'Compare one school with another', 'ஒரு பள்ளியை மற்றொன்றுடன் ஒப்பிடுதல்',
    0,
    'easy',
    'conceptual',
    'Formative/CCE assessment is designed to give continuous feedback that guides and improves learning throughout the course.',
    'வடிவான CCE மதிப்பீடு பாடநெறி முழுவதும் கற்றலை மேம்படுத்தும் தொடர்ச்சியான கருத்தை வழங்க வடிவமைக்கப்பட்டுள்ளது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_006',
    'smp_2022_PAPER_II_MATH_SCI',
    'cdp',
    'cdp_p2_piaget_bruner',
    6,
    '15',
    'Jerome Bruner''s concept of the "spiral curriculum" emphasizes that teaching should:',
    'ஜெரோம் ப்ரூனரின் "சுழல் பாடத்திட்டம்" கருத்து கற்பித்தல் என்னவாக இருக்க வேண்டும் என வலியுறுத்துகிறது?',
    'Revisit topics at increasing levels of complexity', 'அதிகரிக்கும் சிக்கலான நிலைகளில் தலைப்புகளை மீளாய்வு செய்தல்',
    'Teach each topic only once per year', 'ஒவ்வொரு தலைப்பையும் வருடத்திற்கு ஒருமுறை மட்டும் கற்பித்தல்',
    'Separate all subjects completely', 'அனைத்து பாடங்களையும் முற்றிலும் பிரித்தல்',
    'Focus only on memorization', 'மனப்பாடத்தில் மட்டும் கவனம் செலுத்துதல்',
    0,
    'medium',
    'conceptual',
    'The spiral curriculum revisits fundamental ideas repeatedly, each time at a higher level of sophistication so learners deepen understanding.',
    'சுழல் பாடத்திட்டம் அடிப்படை கருத்துக்களை மீண்டும் மீண்டும் அதிக நுட்பமான நிலைகளில் ஆராய்ந்து கற்றவர்களின் புரிதலை ஆழப்படுத்துகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_007',
    'smp_2019_PAPER_II_MATH_SCI',
    'cdp',
    'cdp_p2_memory',
    7,
    '22',
    'Which memory process describes the act of bringing stored information back into conscious awareness?',
    'சேமித்த தகவல்களை உணர்வு நிலைக்கு மீண்டும் கொண்டுவரும் செயலை விவரிக்கும் நினைவாற்றல் செயல்முறை எது?',
    'Retrieval', 'மீட்டெடுப்பு',
    'Encoding', 'குறியாக்கம்',
    'Storage', 'சேமிப்பு',
    'Rehearsal', 'மீள்சொல்லல்',
    0,
    'easy',
    'factual',
    'Retrieval is the process of accessing and bringing stored memories back into conscious awareness.',
    'மீட்டெடுப்பு என்பது சேமித்த நினைவுகளை அணுகி உணர்வு நிலைக்கு மீண்டும் கொண்டுவரும் செயல்முறை.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_008',
    'smp_2022_PAPER_II_MATH_SCI',
    'cdp',
    'cdp_p2_motivation',
    8,
    '30',
    'A student who studies hard because he genuinely enjoys learning is said to be ______ motivated.',
    'கற்றலை உண்மையாகவே விரும்புவதால் கடினமாக படிக்கும் மாணவர் ______ உந்துதலுடன் உள்ளார்.',
    'Intrinsically', 'உள்ளார்ந்த',
    'Extrinsically', 'வெளிப்புற',
    'Negatively', 'எதிர்மறை',
    'Externally', 'வெளியிலிருந்து',
    0,
    'easy',
    'conceptual',
    'Intrinsic motivation comes from internal enjoyment and interest in the activity itself, rather than external rewards.',
    'உள்ளார்ந்த உந்துதல் வெளிப்புற வெகுமதிகளை விட செயலிலேயே உள்ள உள் மகிழ்ச்சி மற்றும் ஆர்வத்திலிருந்து வருகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_009',
    'smp_2019_PAPER_II_MATH_SCI',
    'cdp',
    'cdp_p2_guidance',
    9,
    '40',
    'In school guidance, which type of counselling focuses on helping students understand and solve an immediate personal problem?',
    'பள்ளி வழிகாட்டலில், மாணவர்களுக்கு உடனடி தனிப்பட்ட சிக்கலைப் புரிந்துகொள்ளவும் தீர்க்கவும் உதவும் ஆலோசனை வகை எது?',
    'Directive counseling', 'வழிகாட்டும் ஆலோசனை',
    'Non-directive counseling', 'வழிகாட்டா ஆலோசனை',
    'Eclectic counseling', 'கலப்பு ஆலோசனை',
    'Vocational counseling', 'தொழில் ஆலோசனை',
    0,
    'hard',
    'factual',
    'Directive (counsellor-centred) counselling guides a student toward solving an immediate, specific problem through structured advice.',
    'வழிகாட்டும் (ஆலோசகர்-மைய) ஆலோசனை, கட்டமைக்கப்பட்ட ஆலோசனை மூலம் உடனடி, குறிப்பிட்ட சிக்கலைத் தீர்க்க மாணவரை வழிநடத்துகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_010',
    'smp_2019_PAPER_II_MATH_SCI',
    'cdp',
    'cdp_p2_intelligence',
    10,
    '41',
    'Who developed the "Theory of Multiple Intelligences"?',
    '"பன்மடங்கு நுண்ணறிவு கோட்பாட்டை" உருவாக்கியவர் யார்?',
    'Howard Gardner', 'ஹோவர்ட் கார்ட்னர்',
    'Charles Spearman', 'சார்லஸ் ஸ்பியர்மேன்',
    'Alfred Binet', 'ஆல்பிரட் பினே',
    'Jean Piaget', 'ஜீன் பியாஜே',
    0,
    'easy',
    'factual',
    'Howard Gardner proposed the theory of multiple intelligences (linguistic, logical, musical, spatial, etc.).',
    'ஹோவர்ட் கார்ட்னர் பன்மடங்கு நுண்ணறிவு கோட்பாட்டை (மொழி, தர்க்கம், இசை, இடம் போன்றவை) முன்மொழிந்தார்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_011',
    'smp_2022_PAPER_II_MATH_SCI',
    'cdp',
    'cdp_p2_creativity',
    11,
    '43',
    'Divergent thinking is most closely associated with which ability?',
    'வேறுபட்ட சிந்தனை எந்த திறனுடன் மிக நெருக்கமாக தொடர்புடையது?',
    'Creativity', 'படைப்பாற்றல்',
    'Memory', 'நினைவாற்றல்',
    'Attention', 'கவனம்',
    'Perception', 'உணர்தல்',
    0,
    'medium',
    'conceptual',
    'Divergent thinking, generating many novel ideas, is central to creativity.',
    'பல புதிய கருத்துகளை உருவாக்கும் வேறுபட்ட சிந்தனை படைப்பாற்றலுக்கு மையமானது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_012',
    'smp_2019_PAPER_II_MATH_SCI',
    'cdp',
    'cdp_p2_social',
    12,
    '46',
    'According to Erikson, the psychosocial crisis of adolescence is:',
    'எரிக்சனின் கூற்றுப்படி, இளமைப் பருவத்தின் மனோசமூக நெருக்கடி எது?',
    'Identity vs Role Confusion', 'அடையாளம் vs பாத்திரக் குழப்பம்',
    'Trust vs Mistrust', 'நம்பிக்கை vs அவநம்பிக்கை',
    'Initiative vs Guilt', 'முயற்சி vs குற்றவுணர்வு',
    'Integrity vs Despair', 'நேர்மை vs விரக்தி',
    0,
    'hard',
    'factual',
    'Erikson''s adolescent stage is the crisis of Identity versus Role Confusion.',
    'எரிக்சனின் இளமைப் பருவ நிலை, அடையாளம் எதிர் பாத்திரக் குழப்பம் நெருக்கடி.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_013',
    'smp_2022_PAPER_II_MATH_SCI',
    'cdp',
    'cdp_p2_learning_theories',
    13,
    '49',
    'Operant conditioning, based on reinforcement and punishment, was proposed by:',
    'வலுவூட்டல் மற்றும் தண்டனையின் அடிப்படையிலான செயல்வினை நிபந்தனையை முன்மொழிந்தவர்:',
    'B.F. Skinner', 'பி.எஃப். ஸ்கின்னர்',
    'Ivan Pavlov', 'இவான் பாவ்லோவ்',
    'Edward Thorndike', 'எட்வர்ட் தார்ன்டைக்',
    'Lev Vygotsky', 'லெவ் வைகாட்ஸ்கி',
    0,
    'easy',
    'factual',
    'B.F. Skinner proposed operant conditioning using reinforcement and punishment.',
    'பி.எஃப். ஸ்கின்னர் வலுவூட்டல் மற்றும் தண்டனையைப் பயன்படுத்தி செயல்வினை நிபந்தனையை முன்மொழிந்தார்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_014',
    'smp_2019_PAPER_II_MATH_SCI',
    'cdp',
    'cdp_p2_group',
    14,
    '51',
    'The tendency to perform better on simple tasks in the presence of others is called:',
    'மற்றவர்கள் முன்னிலையில் எளிய பணிகளில் சிறப்பாக செயல்படும் போக்கு என அழைக்கப்படுகிறது:',
    'Social facilitation', 'சமூக வசதி',
    'Social loafing', 'சமூக சோம்பல்',
    'Group conformity', 'குழு ஒத்திசைவு',
    'Deindividuation', 'தனித்துவ இழப்பு',
    0,
    'hard',
    'conceptual',
    'Social facilitation is the improved performance on simple/well-learned tasks in the presence of others.',
    'சமூக வசதி என்பது மற்றவர்கள் முன்னிலையில் எளிய/நன்கு கற்ற பணிகளில் மேம்பட்ட செயல்திறன்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_015',
    'smp_2022_PAPER_II_MATH_SCI',
    'cdp',
    'cdp_p2_mental_health',
    15,
    '54',
    'Which vitamin deficiency is commonly linked to fatigue and weakness in students?',
    'மாணவர்களுக்கு சோர்வு மற்றும் பலவீனத்துடன் பொதுவாக தொடர்புடைய வைட்டமின் குறைபாடு எது?',
    'Vitamin B12 / Iron', 'வைட்டமின் B12 / இரும்பு',
    'Vitamin C', 'வைட்டமின் C',
    'Vitamin A', 'வைட்டமின் A',
    'Vitamin D only', 'வைட்டமின் D மட்டும்',
    0,
    'medium',
    'conceptual',
    'Vitamin B12 and iron deficiency are common causes of fatigue and weakness.',
    'வைட்டமின் B12 மற்றும் இரும்பு குறைபாடு சோர்வு மற்றும் பலவீனத்தின் பொதுவான காரணங்கள்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_016',
    'smp_2022_PAPER_I',
    'tamil',
    'tamil_read_letters',
    16,
    '3',
    'Which of the following is a Mei (consonant) letter in Tamil?',
    'பின்வருவனவற்றில் எது தமிழில் மெய் (மெய்யெழுத்து)?',
    'க', 'க',
    'அ', 'அ',
    'ஆ', 'ஆ',
    'இ', 'இ',
    0,
    'easy',
    'factual',
    'க is a Mei (consonant) letter; அ, ஆ, இ are Uyir (vowel) letters in Tamil.',
    'க என்பது மெய் (மெய்யெழுத்து); அ, ஆ, இ ஆகியவை உயிர் (உயிரெழுத்து) எழுத்துகள்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_017',
    'smp_2019_PAPER_I',
    'tamil',
    'tamil_grammar',
    17,
    '7',
    'How many "Uyirmei" (compound) letters are there in Tamil?',
    'தமிழில் எத்தனை "உயிர்மெய்" (சேர்ம) எழுத்துகள் உள்ளன?',
    '216', '216',
    '12', '12',
    '18', '18',
    '247', '247',
    0,
    'medium',
    'factual',
    'Tamil has 12 Uyir and 18 Mei letters; their 216 combinations form the Uyirmei letters (12 × 18).',
    'தமிழில் 12 உயிர் மற்றும் 18 மெய் எழுத்துகள்; அவற்றின் 216 சேர்க்கைகள் உயிர்மெய் எழுத்துகளை உருவாக்குகின்றன (12 × 18).',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_018',
    'smp_2022_PAPER_I',
    'tamil',
    'tamil_read_text',
    18,
    '11',
    'Which Tamil literary text is written entirely in "Asaariappaa" (ஆசிரியப்பா) metre?',
    'எந்த தமிழ் இலக்கிய நூல் முழுவதும் "ஆசிரியப்பா" வகை யாப்பில் எழுதப்பட்டது?',
    'Thirukkural', 'திருக்குறள்',
    'Tolkappiyam', 'தொல்காப்பியம்',
    'Silappathikaram', 'சிலப்பதிகாரம்',
    'Nannool', 'நன்னூல்',
    2,
    'hard',
    'factual',
    'Silappathikaram, one of the five great epics, is composed in the Asaariappaa metre throughout.',
    'ஐம்பெரும் காப்பியங்களில் ஒன்றான சிலப்பதிகாரம் முழுவதும் ஆசிரியப்பா யாப்பில் இயற்றப்பட்டது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_019',
    'smp_2019_PAPER_I',
    'tamil',
    'tamil_speak_conversation',
    19,
    '19',
    'The polite form of address used for a teacher in Tamil is:',
    'ஆசிரியருக்கு தமிழில் பயன்படுத்தப்படும் மரியாதையான அழைப்பு வடிவம்:',
    'தங்கள்', 'தங்கள்',
    'நீங்கள்', 'நீங்கள்',
    'நீ', 'நீ',
    'அவர்', 'அவர்',
    0,
    'medium',
    'conceptual',
    '"தங்கள்" is the most respectful/polite form of address in Tamil.',
    '"தங்கள்" என்பது தமிழில் மிகவும் மரியாதையான அழைப்பு வடிவம்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_020',
    'smp_2022_PAPER_I',
    'tamil',
    'tamil_vocab_building',
    20,
    '23',
    'Choose the correct antonym for the word "நாட்கள்" (days) in the sense of "வீழ்ச்சி" (decline):',
    '"வீழ்ச்சி" (decline) என்பதன் எதிர்ச்சொல்லைத் தேர்ந்தெடுக்கவும்:',
    'உயர்வு', 'உயர்வு',
    'சரிவு', 'சரிவு',
    'இறக்கம்', 'இறக்கம்',
    'அழிவு', 'அழிவு',
    0,
    'easy',
    'conceptual',
    'உயர்வு (rise) is the antonym of வீழ்ச்சி (fall/decline).',
    'வீழ்ச்சியின் எதிர்ச்சொல் உயர்வு.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_021',
    'smp_2019_PAPER_I',
    'tamil',
    'tamil_listen_rhymes',
    21,
    '26',
    'Which famous Tamil poet wrote the "Neethi Neri Vilakkam" emphasising moral conduct?',
    'நீதி நெறி விளக்கம் எழுதிய புகழ்பெற்ற தமிழ் கவிஞர் யார் (நற்பொருள் நடத்தையை வலியுறுத்தியது)?',
    'Auvaiyar', 'ஔவையார்',
    'Kambar', 'கம்பர்',
    'Ilango Adigal', 'இளங்கோ அடிகள்',
    'Thiruvalluvar', 'திருவள்ளுவர்',
    0,
    'medium',
    'factual',
    'Auvaiyar''s Neethi Neri Vilakkam is a celebrated Tamil didactic work on moral conduct.',
    'ஔவையாரின் நீதி நெறி விளக்கம், நற்பொருள் நடத்தை பற்றிய புகழ்பெற்ற தமிழ் நீதிநூல்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_022',
    'smp_2022_PAPER_I',
    'tamil',
    'tamil_p2_elakkanam',
    22,
    '31',
    'In Tamil grammar, "எழுத்து" refers to which of the following?',
    'தமிழ் இலக்கணத்தில் "எழுத்து" பின்வருவனவற்றில் எதைக் குறிக்கிறது?',
    'Letters/alphabets', 'எழுத்துகள்',
    'Words', 'சொற்கள்',
    'Sentences', 'வாக்கியங்கள்',
    'Meanings', 'பொருள்கள்',
    0,
    'easy',
    'factual',
    'எழுத்து (letters) is the first of the three divisions in Tamil grammar (எழுத்து, சொல், பொருள்).',
    'தமிழ் இலக்கணத்தின் மூன்று பிரிவுகளில் (எழுத்து, சொல், பொருள்) எழுத்து முதலாவது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_023',
    'smp_2019_PAPER_I',
    'tamil',
    'tamil_read_words',
    23,
    '36',
    'What is the correct Tamil word for the number 30?',
    '30 என்ற எண்ணுக்கு சரியான தமிழ்ச் சொல் எது?',
    'முப்பது', 'முப்பது',
    'முன்று', 'முன்று',
    'இருபது', 'இருபது',
    'நாற்பது', 'நாற்பது',
    0,
    'easy',
    'factual',
    'முப்பது is the Tamil word for the number thirty (30).',
    'முப்பது என்பது 30 என்ற எண்ணுக்கான தமிழ்ச்சொல்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_024',
    'smp_2022_PAPER_I',
    'tamil',
    'tamil_write_sentences',
    24,
    '41',
    'Identify the correct Tamil sentence structure for "The boy is reading a book":',
    '"The boy is reading a book" என்பதற்கான சரியான தமிழ் வாக்கிய அமைப்பை அடையாளம் காணவும்:',
    'சிறுவன் புத்தகம் படிக்கிறான்', 'சிறுவன் புத்தகம் படிக்கிறான்',
    'புத்தகம் சிறுவன் படிக்கிறான்', 'புத்தகம் சிறுவன் படிக்கிறான்',
    'சிறுவன் படிக்கிறான் புத்தகம்', 'சிறுவன் படிக்கிறான் புத்தகம்',
    'படிக்கிறான் புத்தகம் சிறுவன்', 'படிக்கிறான் புத்தகம் சிறுவன்',
    0,
    'medium',
    'conceptual',
    'Tamil follows the SOV order: subject (சிறுவன்), object (புத்தகம்), verb (படிக்கிறான்).',
    'தமிழ் SOV வரிசையைப் பின்பற்றுகிறது: செய்பவர் (சிறுவன்), செயப்படுபொருள் (புத்தகம்), வினை (படிக்கிறான்).',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_025',
    'smp_2019_PAPER_I',
    'tamil',
    'tamil_p2_sangam',
    25,
    '47',
    '"Tholkappiyam", the oldest extant Tamil grammar, was written by whom?',
    'தொல்காப்பியம், தொன்மையான தமிழ் இலக்கணம், யாரால் எழுதப்பட்டது?',
    'Tholkappiyar', 'தொல்காப்பியர்',
    'Nannoolar', 'நன்னூலர்',
    'Auvaiyar', 'ஔவையார்',
    'Kambar', 'கம்பர்',
    0,
    'medium',
    'factual',
    'Tholkappiyam, the oldest Tamil grammar, is attributed to Tholkappiyar.',
    'தொல்காப்பியம், தொன்மையான தமிழ் இலக்கணம், தொல்காப்பியரால் இயற்றப்பட்டது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_026',
    'smp_2022_PAPER_I',
    'tamil',
    'tamil_write_letters',
    26,
    '50',
    'Which of these is a "Kuril" (short) Uyir vowel in Tamil?',
    'இவற்றில் எது தமிழில் "குறில்" (குறுகிய) உயிர் எழுத்து?',
    'அ', 'அ',
    'ஆ', 'ஆ',
    'ஈ', 'ஈ',
    'ஊ', 'ஊ',
    0,
    'easy',
    'factual',
    'அ is a short (Kuril) vowel; ஆ, ஈ, ஊ are long (Nedil) vowels.',
    'அ குறில் (குறுகிய) உயிர்; ஆ, ஈ, ஊ நெடில் (நீண்ட) உயிர்கள்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_027',
    'smp_2019_PAPER_I',
    'tamil',
    'tamil_speak_narration',
    27,
    '55',
    'Which Tamil literary genre was used to compose "Tirumurai" (devotional hymns)?',
    'எந்த தமிழ் இலக்கிய வகையில் "திருமுறை" (பக்தி இசைகள்) இயற்றப்பட்டது?',
    'Pathigam', 'பதிகம்',
    'Kappiyam', 'காப்பியம்',
    'Purananuru', 'புறநானூறு',
    'Akananuru', 'அகநானூறு',
    0,
    'hard',
    'factual',
    'The Tirumurai devotional hymns were composed in the Pathigam genre by the Nayanmars.',
    'திருமுறை பக்தி இசைகள் நாயன்மார்களால் பதிகம் வகையில் இயற்றப்பட்டது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_028',
    'smp_2022_PAPER_I',
    'tamil',
    'tamil_language_functions',
    28,
    '60',
    'The word "ஆயின்" (if) is used in Tamil to express which function?',
    '"ஆயின்" (if) என்ற சொல் தமிழில் எந்த செயல்பாட்டை வெளிப்படுத்தப் பயன்படுகிறது?',
    'Condition', 'நிபந்தனை',
    'Exclamation', 'வியப்பு',
    'Question', 'வினா',
    'Command', 'கட்டளை',
    0,
    'medium',
    'conceptual',
    'ஆயின் marks a conditional/if-then relationship in Tamil.',
    'ஆயின் தமிழில் நிபந்தனை/என்றால் உறவைக் குறிக்கிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_029',
    'smp_2019_PAPER_I',
    'tamil',
    'tamil_speak_rhymes',
    29,
    '64',
    'Which of the following is a Tamil tongue-twister (சொற்புரட்டு)?',
    'பின்வருவனவற்றில் எது தமிழ் சொற்புரட்டு?',
    'காக்கை கருகருத்து', 'காக்கை கருகருத்து',
    'வானம் பூமி', 'வானம் பூமி',
    'யானை மலை', 'யானை மலை',
    'மீன் நீர்', 'மீன் நீர்',
    0,
    'easy',
    'factual',
    '"காக்கை கருகருத்து" is a well-known Tamil tongue-twister.',
    '"காக்கை கருகருத்து" பிரபலமான தமிழ் சொற்புரட்டு.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_030',
    'smp_2022_PAPER_I',
    'tamil',
    'tamil_p2_bakthi',
    30,
    '65',
    'Which Tamil saint, known for his Devaram hymns, is counted among the Nayanmars?',
    'தேவார இசைகளுக்கு பெயர் பெற்ற, நாயன்மார்களில் கணக்கிடப்படும் தமிழ் சமயத் துறவி யார்?',
    'Appar', 'அப்பர்',
    'Auvaiyar', 'ஔவையார்',
    'Kambar', 'கம்பர்',
    'Thiruvalluvar', 'திருவள்ளுவர்',
    0,
    'medium',
    'factual',
    'Appar (Thirunavukkarasar), a Nayanmar, composed Devaram hymns.',
    'அப்பர் (திருநாவுக்கரசர்), ஒரு நாயன்மார், தேவார இசைகளை இயற்றினார்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_031',
    'smp_2022_PAPER_I',
    'english',
    'eng_read_phonics',
    31,
    '5',
    'Which of the following words has a short /a/ vowel sound as in "cat"?',
    '"cat" என்பதில் உள்ளது போன்ற குறுகிய /a/ உயிர் ஒலி கொண்ட வார்த்தை எது?',
    'hat', 'hat',
    'hate', 'hate',
    'cake', 'cake',
    'late', 'late',
    0,
    'easy',
    'factual',
    '"hat" has a short /a/ sound; the others contain a long /eɪ/ sound.',
    '"hat" குறுகிய /a/ ஒலி கொண்டது; மற்றவை நீண்ட /eɪ/ ஒலி கொண்டவை.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_032',
    'smp_2019_PAPER_I',
    'english',
    'eng_write_grammar',
    32,
    '9',
    'Choose the correct plural form of the noun "child":',
    '"child" என்ற பெயர்ச்சொல்லின் சரியான பன்மை வடிவத்தைத் தேர்ந்தெடுக்கவும்:',
    'children', 'children',
    'childs', 'childs',
    'childes', 'childes',
    'children', 'children',
    0,
    'easy',
    'factual',
    '"children" is the irregular plural form of "child".',
    '"children" என்பது "child" இன் முறையற்ற பன்மை வடிவம்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_033',
    'smp_2022_PAPER_I',
    'english',
    'eng_speak_communication',
    33,
    '13',
    'Which of the following is an appropriate way to greet a teacher in the morning in English?',
    'காலையில் ஆங்கிலத்தில் ஆசிரியரை வாழ்த்துவதற்கான சரியான வழி எது?',
    'Good morning, Sir/Madam', 'Good morning, Sir/Madam',
    'Hey, you', 'Hey, you',
    'What''s up, teacher?', 'What''s up, teacher?',
    'Yo, bro', 'Yo, bro',
    0,
    'easy',
    'conceptual',
    '"Good morning, Sir/Madam" is a polite and respectful formal greeting.',
    '"Good morning, Sir/Madam" என்பது மரியாதையான முறையான வாழ்த்து.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_034',
    'smp_2019_PAPER_I',
    'english',
    'eng_read_comprehension',
    34,
    '17',
    'In the sentence "The lazy cat slept all day", the word "lazy" is which part of speech?',
    '"The lazy cat slept all day" என்ற வாக்கியத்தில் "lazy" என்ற சொல் எந்த இலக்கண உறுப்பு?',
    'Adjective', 'வினை',
    'Verb', 'பெயர்ச்சொல்',
    'Adverb', 'உரிச்சொல்',
    'Noun', 'வினையுரிச்சொல்',
    0,
    'easy',
    'factual',
    '"lazy" describes the noun "cat", so it is an adjective.',
    '"lazy" "cat" என்ற பெயர்ச்சொல்லை விவரிக்கிறது, எனவே இது பெயரடை.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_035',
    'smp_2022_PAPER_I',
    'english',
    'eng_write_words',
    35,
    '21',
    'What is the antonym of the word "generous"?',
    '"generous" என்ற வார்த்தையின் எதிர்ச்சொல் எது?',
    'stingy', 'stingy',
    'kind', 'kind',
    'helpful', 'helpful',
    'friendly', 'friendly',
    0,
    'easy',
    'conceptual',
    '"stingy" (miserly/unwilling to give) is the opposite of "generous".',
    '"stingy" (கஞ்சத்தனமான) "generous" இன் எதிர்ச்சொல்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_036',
    'smp_2019_PAPER_I',
    'english',
    'eng_read_phonics',
    36,
    '25',
    'Which letter combination represents the sound /ʃ/ as in "ship"?',
    '"ship" இல் உள்ள /ʃ/ ஒலியைக் குறிக்கும் எழுத்துக் கூட்டம் எது?',
    'sh', 'sh',
    'ch', 'ch',
    'th', 'th',
    'ph', 'ph',
    0,
    'easy',
    'factual',
    'The digraph "sh" represents the /ʃ/ sound.',
    '"sh" என்ற இருமை எழுத்து /ʃ/ ஒலியைக் குறிக்கிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_037',
    'smp_2022_PAPER_I',
    'english',
    'eng_speak_fluency',
    37,
    '29',
    'Which sentence uses correct subject-verb agreement?',
    'எந்த வாக்கியம் சரியான செய்பவர்-வினை பொருத்தத்தைப் பயன்படுத்துகிறது?',
    'She goes to school daily.', 'She goes to school daily.',
    'She go to school daily.', 'She go to school daily.',
    'She going to school daily.', 'She going to school daily.',
    'She gone to school daily.', 'She gone to school daily.',
    0,
    'easy',
    'conceptual',
    'The third-person singular subject "She" requires the verb form "goes".',
    'மூன்றாம் நபர் ஒருமை செய்பவர் "She" க்கு "goes" என்ற வினை வடிவம் தேவை.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_038',
    'smp_2019_PAPER_I',
    'english',
    'eng_write_grammar',
    38,
    '32',
    'Identify the preposition in the sentence: "The book is on the table."',
    '"The book is on the table." என்ற வாக்கியத்தில் முன்விபக்தியை அடையாளம் காணவும்.',
    'on', 'on',
    'the', 'the',
    'book', 'book',
    'is', 'is',
    0,
    'easy',
    'factual',
    '"on" shows the relationship between the book and the table, so it is a preposition.',
    '"on" புத்தகத்திற்கும் மேசைக்கும் இடையிலான உறவைக் காட்டுகிறது, எனவே இது முன்விபக்தி.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_039',
    'smp_2022_PAPER_I',
    'english',
    'eng_listen_stories',
    39,
    '37',
    'Which of the following is a common element of a fable?',
    'பின்வருவனவற்றில் எது நீதிக்கதையின் (fable) பொதுவான அம்சம்?',
    'Talking animals with a moral', 'ஒழுக்கத்துடன் பேசும் விலங்குகள்',
    'Only human characters', 'மனித கதாபாத்திரங்கள் மட்டும்',
    'No lesson at the end', 'இறுதியில் பாடமில்லை',
    'Always set in a city', 'எப்போதும் நகரில் அமைந்தவை',
    0,
    'easy',
    'conceptual',
    'Fables typically feature talking animals and end with a moral lesson.',
    'நீதிக்கதைகள் பொதுவாக பேசும் விலங்குகளைக் கொண்டு ஒழுக்கப் பாடத்துடன் முடிகின்றன.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_040',
    'smp_2019_PAPER_I',
    'english',
    'eng_read_comprehension',
    40,
    '42',
    'The main idea of a passage is best defined as:',
    'ஒரு பத்தியின் முக்கிய கருத்து எவ்வாறு வரையறுக்கப்படுகிறது?',
    'The central point the author wants to convey', 'ஆசிரியர் தெரிவிக்க விரும்பும் மையக் கருத்து',
    'The first sentence only', 'முதல் வாக்கியம் மட்டும்',
    'The list of all details', 'அனைத்து விவரங்களின் பட்டியல்',
    'The title of the book', 'புத்தகத்தின் தலைப்பு',
    0,
    'medium',
    'conceptual',
    'The main idea is the central, most important point an author conveys about the topic.',
    'முக்கிய கருத்து என்பது ஆசிரியர் தலைப்பைப் பற்றி தெரிவிக்கும் மைய, மிக முக்கியமான புள்ளி.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_041',
    'smp_2022_PAPER_I',
    'english',
    'eng_write_grammar',
    41,
    '46',
    'Which word is a conjunction in: "Ravi studied hard, so he passed the exam."?',
    '"Ravi studied hard, so he passed the exam." என்பதில் எது இணைப்புச்சொல்?',
    'so', 'so',
    'hard', 'hard',
    'exam', 'exam',
    'passed', 'passed',
    0,
    'medium',
    'factual',
    '"so" connects the two clauses, so it is a conjunction.',
    '"so" இரண்டு உட்கூறுகளை இணைக்கிறது, எனவே இது இணைப்புச்சொல்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_042',
    'smp_2019_PAPER_I',
    'english',
    'eng_p2_grammar',
    42,
    '51',
    'Choose the correct tense: "By next week, she ______ the project."',
    'சரியான காலத்தைத் தேர்ந்தெடுக்கவும்: "By next week, she ______ the project."',
    'will have completed', 'will have completed',
    'completes', 'completes',
    'is completing', 'is completing',
    'completed', 'completed',
    0,
    'hard',
    'conceptual',
    'Future Perfect tense (will have completed) is used for an action finished by a certain future time.',
    'எதிர்கால நிறைவு காலம் (will have completed) ஒரு குறிப்பிட்ட எதிர்கால நேரத்தில் நிறைவடைந்த செயலுக்குப் பயன்படுகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_043',
    'smp_2022_PAPER_I',
    'english',
    'eng_write_words',
    43,
    '56',
    'What is the correct synonym of the word "rapid"?',
    '"rapid" என்ற வார்த்தையின் சரியான ஒத்தச்சொல் எது?',
    'fast', 'fast',
    'slow', 'slow',
    'heavy', 'heavy',
    'quiet', 'quiet',
    0,
    'easy',
    'conceptual',
    '"fast" is a synonym of "rapid", meaning quick or speedy.',
    '"fast" என்பது "rapid" இன் ஒத்தச்சொல், வேகமான.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_044',
    'smp_2019_PAPER_I',
    'english',
    'eng_read_phonics',
    44,
    '61',
    'Which pair of words rhymes?',
    'எந்த ஜோடி வார்த்தைகள் ஒலி ஒத்தவை?',
    'rain - pain', 'rain - pain',
    'rain - road', 'rain - road',
    'book - look at', 'book - look at',
    'cat - dog', 'cat - dog',
    0,
    'easy',
    'factual',
    '"rain" and "pain" share the same ending sound /eɪn/, so they rhyme.',
    '"rain" மற்றும் "pain" ஆகியவை /eɪn/ என்ற ஒரே இறுதி ஒலியைப் பகிர்ந்து ஒலி ஒத்தவை.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_045',
    'smp_2022_PAPER_I',
    'maths',
    'maths_number_concept',
    45,
    '6',
    'What is the place value of the digit 5 in the number 5,432?',
    '5,432 என்ற எண்ணில் 5 என்ற இலக்கத்தின் இடமதிப்பு என்ன?',
    '5,000', '5,000',
    '500', '500',
    '50', '50',
    '5', '5',
    0,
    'easy',
    'application',
    'The digit 5 is in the thousands place, so its place value is 5 × 1000 = 5,000.',
    'இலக்கம் 5 ஆயிரம் இடத்தில் உள்ளது, எனவே அதன் இடமதிப்பு 5 × 1000 = 5,000.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_046',
    'smp_2019_PAPER_I',
    'maths',
    'maths_addition_subtraction',
    46,
    '10',
    'What is the sum of 482 and 319?',
    '482 மற்றும் 319 ஆகியவற்றின் கூட்டுத்தொகை எவ்வளவு?',
    '801', '801',
    '791', '791',
    '811', '811',
    '701', '701',
    0,
    'easy',
    'application',
    '482 + 319 = 801.',
    '482 + 319 = 801.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_047',
    'smp_2022_PAPER_I',
    'maths',
    'maths_multiplication',
    47,
    '14',
    'What is the product of 12 and 8?',
    '12 மற்றும் 8 இன் பெருக்குத்தொகை எவ்வளவு?',
    '96', '96',
    '86', '86',
    '106', '106',
    '76', '76',
    0,
    'easy',
    'application',
    '12 × 8 = 96.',
    '12 × 8 = 96.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_048',
    'smp_2019_PAPER_I',
    'maths',
    'maths_fractions',
    48,
    '18',
    'Which of the following fractions is equivalent to 1/2?',
    'பின்வருவனவற்றில் எந்த பின்னம் 1/2 க்குச் சமமானது?',
    '2/4', '2/4',
    '2/3', '2/3',
    '1/4', '1/4',
    '3/6 (also correct)', '3/6 (also correct)',
    0,
    'medium',
    'conceptual',
    '2/4 simplifies to 1/2, so it is equivalent.',
    '2/4 எளிதாக்க 1/2 ஆகும், எனவே சமமானது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_049',
    'smp_2022_PAPER_I',
    'maths',
    'maths_2d_shapes',
    49,
    '24',
    'How many sides does a hexagon have?',
    'அறுகோணத்திற்கு எத்தனை பக்கங்கள் உள்ளன?',
    '6', '6',
    '5', '5',
    '7', '7',
    '8', '8',
    0,
    'easy',
    'factual',
    'A hexagon is a polygon with six sides.',
    'அறுகோணம் ஆறு பக்கங்களைக் கொண்ட பலகோணம்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_050',
    'smp_2019_PAPER_I',
    'maths',
    'maths_symmetry',
    50,
    '28',
    'How many lines of symmetry does a square have?',
    'சதுரத்திற்கு எத்தனை சமச்சீர் கோடுகள் உள்ளன?',
    '4', '4',
    '2', '2',
    '1', '1',
    '0', '0',
    0,
    'medium',
    'conceptual',
    'A square has 4 lines of symmetry: two diagonals and the two midlines.',
    'சதுரத்திற்கு 4 சமச்சீர் கோடுகள்: இரண்டு மூலைவிட்டங்கள் மற்றும் இரண்டு நடுக்கோடுகள்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_051',
    'smp_2022_PAPER_I',
    'maths',
    'maths_length_weight',
    51,
    '33',
    'How many millimetres are there in 1 centimetre?',
    '1 சென்டிமீட்டரில் எத்தனை மில்லிமீட்டர்கள் உள்ளன?',
    '10', '10',
    '100', '100',
    '1000', '1000',
    '1', '1',
    0,
    'easy',
    'factual',
    '1 centimetre equals 10 millimetres.',
    '1 சென்டிமீட்டர் 10 மில்லிமீட்டருக்கு சமம்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_052',
    'smp_2019_PAPER_I',
    'maths',
    'maths_time',
    52,
    '38',
    'How many minutes are there in 2 hours?',
    '2 மணி நேரத்தில் எத்தனை நிமிடங்கள் உள்ளன?',
    '120', '120',
    '100', '100',
    '60', '60',
    '200', '200',
    0,
    'easy',
    'application',
    '2 × 60 = 120 minutes.',
    '2 × 60 = 120 நிமிடங்கள்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_053',
    'smp_2022_PAPER_I',
    'maths',
    'maths_money',
    53,
    '43',
    'If a notebook costs ₹25, what is the cost of 4 notebooks?',
    'ஒரு குறிப்பேடு ₹25 எனில், 4 குறிப்பேடுகளின் விலை என்ன?',
    '₹100', '₹100',
    '₹80', '₹80',
    '₹120', '₹120',
    '₹75', '₹75',
    0,
    'easy',
    'application',
    '4 × 25 = ₹100.',
    '4 × 25 = ₹100.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_054',
    'smp_2019_PAPER_I',
    'maths',
    'maths_patterns',
    54,
    '48',
    'Continue the pattern: 2, 4, 6, 8, ?',
    'முறையைத் தொடரவும்: 2, 4, 6, 8, ?',
    '10', '10',
    '9', '9',
    '12', '12',
    '11', '11',
    0,
    'easy',
    'application',
    'The pattern adds 2 each time, so the next number is 10.',
    'முறை ஒவ்வொரு முறையும் 2 ஐக் கூட்டுகிறது, எனவே அடுத்த எண் 10.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_055',
    'smp_2022_PAPER_I',
    'maths',
    'maths_data',
    55,
    '53',
    'A graph showing data using bars is called a:',
    'கம்பிகளைப் பயன்படுத்தி தரவைக் காட்டும் வரைபடம் எவ்வாறு அழைக்கப்படுகிறது?',
    'Bar graph', 'கம்பி வரைபடம்',
    'Pie chart', 'வட்ட விளக்கப்படம்',
    'Line graph', 'கோடு வரைபடம்',
    'Pictograph', 'படவரைபடம்',
    0,
    'easy',
    'factual',
    'A bar graph uses rectangular bars to represent data values.',
    'கம்பி வரைபடம் தரவு மதிப்புகளைக் குறிக்க செவ்வக கம்பிகளைப் பயன்படுத்துகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_056',
    'smp_2019_PAPER_I',
    'maths',
    'maths_fractions',
    56,
    '58',
    'What is 3/4 expressed as a decimal?',
    '3/4 ஐ தசமமாக வெளிப்படுத்தினால் என்ன?',
    '0.75', '0.75',
    '0.34', '0.34',
    '0.43', '0.43',
    '3.4', '3.4',
    0,
    'medium',
    'application',
    '3 divided by 4 equals 0.75.',
    '3 ஐ 4 ஆல் வகுக்க 0.75 கிடைக்கும்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_057',
    'smp_2022_PAPER_I',
    'maths',
    'maths_length_weight',
    57,
    '62',
    'Which unit is used to measure the weight of a bag of rice?',
    'அரிசி மூட்டையின் எடையை அளக்க எந்த அலகு பயன்படுத்தப்படுகிறது?',
    'Kilogram', 'கிலோகிராம்',
    'Millilitre', 'மில்லிலிட்டர்',
    'Centimetre', 'சென்டிமீட்டர்',
    'Litre', 'லிட்டர்',
    0,
    'easy',
    'conceptual',
    'Weight/mass is measured in kilograms (kg) for such items.',
    'எடை/நிறை கிலோகிராமில் (kg) அளவிடப்படுகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_058',
    'smp_2019_PAPER_I',
    'maths',
    'maths_number_concept',
    58,
    '66',
    'What is the smallest 3-digit number?',
    'மிகச் சிறிய 3 இலக்க எண் எது?',
    '100', '100',
    '999', '999',
    '101', '101',
    '111', '111',
    0,
    'easy',
    'factual',
    '100 is the smallest three-digit number.',
    '100 மிகச் சிறிய மூன்று இலக்க எண்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_059',
    'smp_2022_PAPER_I',
    'evs',
    'evs_plant_parts',
    59,
    '4',
    'Which part of the plant is mainly responsible for absorbing water and minerals?',
    'தாவரத்தின் எந்தப் பகுதி முக்கியமாக தண்ணீர் மற்றும் கனிமங்களை உறிஞ்சுகிறது?',
    'Roots', 'வேர்கள்',
    'Leaves', 'இலைகள்',
    'Flowers', 'பூக்கள்',
    'Fruits', 'பழங்கள்',
    0,
    'easy',
    'factual',
    'Roots absorb water and minerals from the soil.',
    'வேர்கள் மண்ணிலிருந்து தண்ணீர் மற்றும் கனிமங்களை உறிஞ்சுகின்றன.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_060',
    'smp_2019_PAPER_I',
    'evs',
    'evs_animal_habitat',
    60,
    '16',
    'A polar bear is most likely to be found in which habitat?',
    'பனிக்கரடி பொதுவாக எந்த வாழ்விடத்தில் காணப்படும்?',
    'Arctic region', 'ஆர்க்டிக் பகுதி',
    'Desert', 'பாலைவனம்',
    'Rainforest', 'மழைக்காடு',
    'Freshwater lake', 'நன்னீர் ஏரி',
    0,
    'easy',
    'factual',
    'Polar bears live in the cold Arctic region.',
    'பனிக்கரடிகள் குளிர்ந்த ஆர்க்டிக் பகுதியில் வாழ்கின்றன.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_061',
    'smp_2022_PAPER_I',
    'evs',
    'evs_water',
    61,
    '20',
    'Which of the following is the purest form of natural water?',
    'பின்வருவனவற்றில் எது மிகவும் தூய்மையான இயற்கை நீர் வடிவம்?',
    'Rainwater', 'மழைநீர்',
    'River water', 'ஆற்று நீர்',
    'Sea water', 'கடல் நீர்',
    'Well water', 'கிணற்று நீர்',
    0,
    'medium',
    'conceptual',
    'Rainwater, formed by evaporation and condensation, is the purest natural form.',
    'ஆவியாதல் மற்றும் ஒடுக்கத்தால் உருவாகும் மழைநீர் மிகத் தூய்மையான இயற்கை வடிவம்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_062',
    'smp_2019_PAPER_I',
    'evs',
    'evs_air',
    62,
    '34',
    'Which gas in air is essential for respiration in living beings?',
    'உயிரினங்களின் சுவாசத்திற்கு அவசியமான காற்றில் உள்ள வாயு எது?',
    'Oxygen', 'ஆக்சிஜன்',
    'Carbon dioxide', 'கார்பன் டை ஆக்சைடு',
    'Nitrogen', 'நைட்ரஜன்',
    'Hydrogen', 'ஹைட்ரஜன்',
    0,
    'easy',
    'factual',
    'Oxygen is essential for respiration in living beings.',
    'உயிரினங்களின் சுவாசத்திற்கு ஆக்சிஜன் அவசியம்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_063',
    'smp_2022_PAPER_I',
    'evs',
    'evs_food',
    63,
    '39',
    'Which nutrient is the main source of quick energy for the body?',
    'உடலுக்கு விரைவான சக்தியின் முக்கிய மூலம் எந்த ஊட்டச்சத்து?',
    'Carbohydrates', 'கார்போஹைட்ரேட்டுகள்',
    'Proteins', 'புரதங்கள்',
    'Vitamins', 'வைட்டமின்கள்',
    'Minerals', 'கனிமங்கள்',
    0,
    'easy',
    'factual',
    'Carbohydrates provide the main quick source of energy.',
    'கார்போஹைட்ரேட்டுகள் விரைவான சக்தியின் முக்கிய மூலத்தை வழங்குகின்றன.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_064',
    'smp_2019_PAPER_I',
    'evs',
    'evs_body',
    64,
    '45',
    'Which organ pumps blood throughout the human body?',
    'மனித உடலில் ரத்தத்தை முழுவதும் செலுத்தும் உறுப்பு எது?',
    'Heart', 'இதயம்',
    'Lungs', 'நுரையீரல்',
    'Kidney', 'சிறுநீரகம்',
    'Liver', 'கல்லீரல்',
    0,
    'easy',
    'factual',
    'The heart pumps blood throughout the body.',
    'இதயம் உடல் முழுவதும் ரத்தத்தைச் செலுத்துகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_065',
    'smp_2022_PAPER_I',
    'evs',
    'evs_health',
    65,
    '49',
    'Which of the following is a hygienic practice to prevent disease?',
    'நோயைத் தடுக்க பின்வருவனவற்றில் எது சுகாதாரமான பழக்கம்?',
    'Washing hands before meals', 'உணவுக்கு முன் கைகளைக் கழுவுதல்',
    'Drinking unclean water', 'சுத்தமற்ற தண்ணீர் குடித்தல்',
    'Sharing towels', 'துண்டைப் பகிர்தல்',
    'Skipping baths', 'குளிப்பதைத் தவிர்த்தல்',
    0,
    'easy',
    'conceptual',
    'Washing hands before meals removes germs and prevents disease.',
    'உணவுக்கு முன் கைகளைக் கழுவுதல் கிருமிகளை நீக்கி நோயைத் தடுக்கிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_066',
    'smp_2019_PAPER_I',
    'evs',
    'evs_matter',
    66,
    '54',
    'Water, ice and steam are examples of which states of matter?',
    'நீர், பனி மற்றும் நீராவி ஆகியவை எந்த நிலைகளின் எடுத்துக்காட்டுகள்?',
    'Liquid, solid, gas', 'திரவம், திடம், வாயு',
    'Solid, gas, liquid', 'திடம், வாயு, திரவம்',
    'Gas, liquid, solid', 'வாயு, திரவம், திடம்',
    'Solid, liquid, gas', 'திடம், திரவம், வாயு',
    0,
    'medium',
    'conceptual',
    'Water is liquid, ice is solid, and steam is gas.',
    'நீர் திரவம், பனி திடம், நீராவி வாயு.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_067',
    'smp_2022_PAPER_I',
    'evs',
    'evs_energy',
    67,
    '59',
    'Which energy source is renewable and obtained from the sun?',
    'சூரியனிலிருந்து பெறப்படும் புதுப்பிக்கத்தக்க எரிசக்தி மூலம் எது?',
    'Solar energy', 'சூரிய ஆற்றல்',
    'Coal', 'நிலக்கரி',
    'Petroleum', 'பெட்ரோலியம்',
    'Natural gas', 'இயற்கை எரிவாயு',
    0,
    'medium',
    'factual',
    'Solar energy, captured from the sun, is renewable and clean.',
    'சூரியனிலிருந்து கைப்பற்றப்படும் சூரிய ஆற்றல் புதுப்பிக்கத்தக்கது, தூய்மையானது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_068',
    'smp_2019_PAPER_I',
    'evs',
    'evs_small_creatures',
    68,
    '63',
    'Which of these is an insect?',
    'இவற்றில் எது பூச்சி?',
    'Butterfly', 'வண்ணத்துப்பூச்சி',
    'Frog', 'தவளை',
    'Bird', 'பறவை',
    'Fish', 'மீன்',
    0,
    'easy',
    'factual',
    'A butterfly has six legs and three body parts, making it an insect.',
    'வண்ணத்துப்பூச்சிக்கு ஆறு கால்கள் மற்றும் மூன்று உடல் பகுதிகள் உள்ளன, இது பூச்சியாக்குகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_069',
    'smp_2022_PAPER_I',
    'evs',
    'evs_day_night',
    69,
    '67',
    'Day and night occur on Earth due to which factor?',
    'பகல் மற்றும் இரவு பூமியில் எந்த காரணத்தால் நிகழ்கிறது?',
    'Rotation of the Earth', 'பூமியின் சுழற்சி',
    'Revolution of the Earth', 'பூமியின் பரிவர்த்தனை',
    'Tilt of the axis', 'அச்சின் சாய்வு',
    'Moon''s orbit', 'நிலவின் சுற்றுப்பாதை',
    0,
    'medium',
    'conceptual',
    'The Earth''s rotation on its axis causes day and night.',
    'பூமியின் அச்சில் சுழற்சி பகல் மற்றும் இரவை ஏற்படுத்துகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_070',
    'smp_2019_PAPER_I',
    'evs',
    'evs_family_community',
    70,
    '68',
    'A group of families living together and sharing common facilities is known as a:',
    'ஒன்றாக வாழும் மற்றும் பொதுவான வசதிகளைப் பகிர்ந்துகொள்ளும் குடும்பங்களின் குழு என அழைக்கப்படுகிறது:',
    'Community', 'சமூகம்',
    'Individual', 'தனிநபர்',
    'School', 'பள்ளி',
    'Forest', 'காடு',
    0,
    'easy',
    'conceptual',
    'A community is a group of families sharing common facilities and interests.',
    'சமூகம் என்பது பொதுவான வசதிகளையும் நலன்களையும் பகிர்ந்துகொள்ளும் குடும்பங்களின் குழு.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_071',
    'smp_2022_PAPER_I',
    'evs',
    'evs_tamilnadu',
    71,
    '69',
    'Which river is the longest river entirely within Tamil Nadu?',
    'தமிழ்நாட்டிற்குள்ளேயே முழுவதுமாக ஓடும் மிக நீளமான நதி எது?',
    'Kaveri', 'காவிரி',
    'Ganga', 'கங்கை',
    'Yamuna', 'யமுனை',
    'Sindhu', 'சிந்து',
    0,
    'medium',
    'factual',
    'The Kaveri is the major river flowing through Tamil Nadu.',
    'காவிரி தமிழ்நாட்டின் முக்கிய நதியாகும்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_072',
    'smp_2019_PAPER_I',
    'evs',
    'evs_india',
    72,
    '70',
    'Which national animal of India is known for its protection in Project Tiger?',
    'புலிகள் திட்டத்தில் பாதுகாக்கப்படும் இந்தியாவின் தேசிய விலங்கு எது?',
    'Tiger', 'புலி',
    'Lion', 'சிங்கம்',
    'Elephant', 'யானை',
    'Deer', 'மான்',
    0,
    'easy',
    'factual',
    'The tiger, India''s national animal, is protected under Project Tiger.',
    'இந்தியாவின் தேசிய விலங்கான புலி, புலிகள் திட்டத்தில் பாதுகாக்கப்படுகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_073',
    'smp_2022_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_real_numbers',
    73,
    '2',
    'Which of the following is an irrational number?',
    'பின்வருவனவற்றில் எது விகிதமுறா எண்?',
    '√2', '√2',
    '4', '4',
    '0.5', '0.5',
    '22/7', '22/7',
    0,
    'hard',
    'conceptual',
    '√2 cannot be expressed as a ratio of two integers, so it is irrational.',
    '√2 ஐ இரண்டு முழு எண்களின் விகிதமாக வெளிப்படுத்த முடியாது, எனவே விகிதமுறா எண்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_074',
    'smp_2019_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_algebra',
    74,
    '12',
    'If x + 5 = 12, what is the value of x?',
    'x + 5 = 12 எனில், x இன் மதிப்பு என்ன?',
    '7', '7',
    '5', '5',
    '17', '17',
    '60', '60',
    0,
    'easy',
    'application',
    'x = 12 − 5 = 7.',
    'x = 12 − 5 = 7.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_075',
    'smp_2022_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_lines_angles',
    75,
    '22',
    'What is the measure of a right angle in degrees?',
    'செங்கோணத்தின் அளவு டிகிரியில் என்ன?',
    '90°', '90°',
    '45°', '45°',
    '180°', '180°',
    '360°', '360°',
    0,
    'easy',
    'factual',
    'A right angle measures exactly 90 degrees.',
    'செங்கோணம் சரியாக 90 டிகிரி அளவிடுகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_076',
    'smp_2019_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_mensuration',
    76,
    '32',
    'What is the area of a rectangle with length 8 cm and width 5 cm?',
    'நீளம் 8 செமீ மற்றும் அகலம் 5 செமீ கொண்ட செவ்வகத்தின் பரப்பளவு என்ன?',
    '40 sq cm', '40 சதுர செமீ',
    '13 sq cm', '13 சதுர செமீ',
    '45 sq cm', '45 சதுர செமீ',
    '80 sq cm', '80 சதுர செமீ',
    0,
    'easy',
    'application',
    'Area = length × width = 8 × 5 = 40 sq cm.',
    'பரப்பளவு = நீளம் × அகலம் = 8 × 5 = 40 சதுர செமீ.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_077',
    'smp_2022_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_matter',
    77,
    '42',
    'Which state of matter has a definite shape and a definite volume?',
    'எந்த நிலை பொருளுக்கு உறுதியான வடிவமும் உறுதியான கன அளவும் உள்ளது?',
    'Solid', 'திடம்',
    'Liquid', 'திரவம்',
    'Gas', 'வாயு',
    'Plasma', 'பிளாஸ்மா',
    0,
    'easy',
    'factual',
    'A solid has a definite shape and a definite volume.',
    'திடத்திற்கு உறுதியான வடிவமும் உறுதியான கன அளவும் உள்ளது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_078',
    'smp_2019_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_biology',
    78,
    '5',
    'The powerhouse of the cell, where energy is produced, is the:',
    'ஆற்றல் உற்பத்தியாகும் செல்லின் சக்தி நிலையம்:',
    'Mitochondria', 'மைட்டோகாண்ட்ரியா',
    'Nucleus', 'கரு',
    'Ribosome', 'ரைபோசோம்',
    'Cell wall', 'செல் சுவர்',
    0,
    'medium',
    'factual',
    'The mitochondria generate energy (ATP) for the cell.',
    'மைட்டோகாண்ட்ரியா செல்லுக்கு ஆற்றலை (ATP) உருவாக்குகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_079',
    'smp_2022_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_forces',
    79,
    '15',
    'Which force opposes the motion of an object sliding on a surface?',
    'மேற்பரப்பில் சறுக்கும் பொருளின் இயக்கத்தை எதிர்க்கும் விசை எது?',
    'Friction', 'உராய்வு',
    'Gravity', 'புவிஈர்ப்பு',
    'Magnetism', 'காந்தவிசை',
    'Upthrust', 'மேலுந்துகை',
    0,
    'medium',
    'conceptual',
    'Friction is the force that opposes sliding motion between surfaces.',
    'உராய்வு என்பது மேற்பரப்புகளுக்கு இடையே சறுக்கும் இயக்கத்தை எதிர்க்கும் விசை.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_080',
    'smp_2019_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_light_sound',
    80,
    '25',
    'Which phenomenon explains the formation of shadows?',
    'நிழல்கள் உருவாவதை விளக்கும் நிகழ்வு எது?',
    'Rectilinear propagation of light', 'ஒளியின் நேர்கோட்டு பரவல்',
    'Reflection of light', 'ஒளியின் எதிரொளிப்பு',
    'Refraction of light', 'ஒளியின் விலகல்',
    'Diffraction of light', 'ஒளியின் விளிம்பு வளைவு',
    0,
    'hard',
    'conceptual',
    'Shadows form because light travels in straight lines and cannot bend around obstacles.',
    'ஒளி நேர்கோட்டில் பயணித்து தடைகளைச் சுற்றி வளைக்க முடியாததால் நிழல்கள் உருவாகின்றன.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_081',
    'smp_2022_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_algebra',
    81,
    '35',
    'Factorise: x² − 9',
    'காரணிப்படுத்துக: x² − 9',
    '(x+3)(x−3)', '(x+3)(x−3)',
    '(x+9)(x−1)', '(x+9)(x−1)',
    '(x−3)(x−3)', '(x−3)(x−3)',
    '(x+3)(x+3)', '(x+3)(x+3)',
    0,
    'hard',
    'application',
    'x² − 9 is a difference of squares: (x−3)(x+3).',
    'x² − 9 சதுரங்களின் வேறுபாடு: (x−3)(x+3).',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_082',
    'smp_2019_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_mensuration',
    82,
    '45',
    'What is the circumference of a circle with radius 7 cm? (Use π = 22/7)',
    'ஆரம் 7 செமீ கொண்ட வட்டத்தின் சுற்றளவு என்ன? (π = 22/7 பயன்படுத்தவும்)',
    '44 cm', '44 செமீ',
    '22 cm', '22 செமீ',
    '154 cm', '154 செமீ',
    '14 cm', '14 செமீ',
    0,
    'medium',
    'application',
    'Circumference = 2πr = 2 × 22/7 × 7 = 44 cm.',
    'சுற்றளவு = 2πr = 2 × 22/7 × 7 = 44 செமீ.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_083',
    'smp_2022_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_biology',
    83,
    '52',
    'Photosynthesis mainly occurs in which part of the plant?',
    'ஒளிச்சேர்க்கை முக்கியமாக தாவரத்தின் எந்தப் பகுதியில் நடைபெறுகிறது?',
    'Leaf', 'இலை',
    'Root', 'வேர்',
    'Stem only', 'தண்டு மட்டும்',
    'Flower', 'பூ',
    0,
    'easy',
    'factual',
    'Photosynthesis mainly occurs in the leaves where chlorophyll is present.',
    'ஒளிச்சேர்க்கை குளோரோபில் உள்ள இலைகளில் முக்கியமாக நடைபெறுகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_084',
    'smp_2019_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_forces',
    84,
    '58',
    'According to Newton''s first law, an object at rest will remain at rest unless:',
    'நியூட்டனின் முதல் விதிப்படி, ஓய்வில் உள்ள பொருள் எதுவரை ஓய்வில் இருக்கும்?',
    'An external unbalanced force acts on it', 'வெளிப்புற சமநிலையற்ற விசை செயல்படும் வரை',
    'It is observed by someone', 'யாரோ கவனிக்கும் வரை',
    'Its temperature changes', 'அதன் வெப்பநிலை மாறும் வரை',
    'It absorbs light', 'ஒளியை உறிஞ்சும் வரை',
    0,
    'medium',
    'factual',
    'Newton''s first law (inertia) states an object stays at rest or uniform motion unless acted on by an external unbalanced force.',
    'நியூட்டனின் முதல் விதி (யோர்வு), வெளிப்புற சமநிலையற்ற விசை செயல்படாத வரை பொருள் ஓய்விலோ சீரான இயக்கத்திலோ இருக்கும்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_085',
    'smp_2022_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_real_numbers',
    85,
    '61',
    'How many prime numbers are there between 1 and 10?',
    '1 மற்றும் 10 க்கு இடையில் எத்தனை பகா எண்கள் உள்ளன?',
    '4', '4',
    '3', '3',
    '5', '5',
    '6', '6',
    0,
    'easy',
    'factual',
    'The primes between 1 and 10 are 2, 3, 5, 7 — four primes.',
    '1 மற்றும் 10 க்கு இடையிலான பகா எண்கள் 2, 3, 5, 7 — நான்கு.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_086',
    'smp_2019_PAPER_II_MATH_SCI',
    'maths_science',
    'ms_light_sound',
    86,
    '65',
    'The speed of sound is greatest in which medium?',
    'எந்த ஊடகத்தில் ஒலியின் வேகம் அதிகம்?',
    'Solids', 'திடப்பொருட்கள்',
    'Liquids', 'திரவங்கள்',
    'Gases', 'வாயுக்கள்',
    'Vacuum', 'வெற்றிடம்',
    0,
    'hard',
    'conceptual',
    'Sound travels fastest in solids where particles are tightly packed.',
    'துகள்கள் நெருக்கமாக அமைந்த திடப்பொருட்களில் ஒலி வேகமாகப் பயணிக்கிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_087',
    'smp_2022_PAPER_II_SOC_SCI',
    'social_science',
    'ss_ancient_india',
    87,
    '3',
    'Which ancient Indian law-giver compiled the "Arthashastra" discussing statecraft and economy?',
    'அரசியல் மற்றும் பொருளாதாரம் குறித்த "அர்த்தசாஸ்திரம்" தொகுத்த பண்டைய இந்திய சட்டமைப்பாளர் யார்?',
    'Kautilya (Chanakya)', 'கௌடில்யர் (சாணக்கியர்)',
    'Ashoka', 'அசோகர்',
    'Akbar', 'அக்பர்',
    'Harsha', 'ஹர்ஷர்',
    0,
    'medium',
    'factual',
    'Kautilya (Chanakya) authored the Arthashastra on statecraft and economy.',
    'கௌடில்யர் (சாணக்கியர்) அரசியல் மற்றும் பொருளாதாரம் குறித்த அர்த்தசாஸ்திரத்தை எழுதினார்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_088',
    'smp_2019_PAPER_II_SOC_SCI',
    'social_science',
    'ss_physio_india',
    88,
    '11',
    'The Himalayas are classified as which type of mountain?',
    'இமயமலை எந்த வகை மலையாக வகைப்படுத்தப்படுகிறது?',
    'Fold mountains', 'மடிப்பு மலைகள்',
    'Block mountains', 'தொகுதி மலைகள்',
    'Volcanic mountains', 'எரிமலை மலைகள்',
    'Plateau mountains', 'பீடபூமி மலைகள்',
    0,
    'medium',
    'factual',
    'The Himalayas are young fold mountains formed by tectonic plate collision.',
    'இமயமலை தட்டு மோதலால் உருவான இளம் மடிப்பு மலைகள்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_089',
    'smp_2022_PAPER_II_SOC_SCI',
    'social_science',
    'ss_medieval_modern',
    89,
    '18',
    'The first Battle of Panipat (1526) marked the beginning of which empire?',
    'முதல் பானிபட் போர் (1526) எந்த பேரரசின் தொடக்கத்தைக் குறித்தது?',
    'Mughal Empire', 'முகலாய பேரரசு',
    'Maratha Empire', 'மராத்தா பேரரசு',
    'British Raj', 'பிரிட்டிஷ் ஆட்சி',
    'Vijayanagara', 'விஜயநகரம்',
    0,
    'medium',
    'factual',
    'Babur''s victory at Panipat in 1526 founded the Mughal Empire.',
    '1526 இல் பானிபட்டில் பாபரின் வெற்றி முகலாய பேரரசை நிறுவியது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_090',
    'smp_2019_PAPER_II_SOC_SCI',
    'social_science',
    'ss_democracy',
    90,
    '26',
    '"Government of the people, by the people, for the people" defines which concept?',
    '"மக்களால், மக்களுக்காக, மக்களின் அரசு" எந்த கருத்தை வரையறுக்கிறது?',
    'Democracy', 'ஜனநாயகம்',
    'Monarchy', 'முடியாட்சி',
    'Dictatorship', 'சர்வாதிகாரம்',
    'Theocracy', 'இறையாட்சி',
    0,
    'easy',
    'conceptual',
    'Abraham Lincoln''s famous phrase defines democracy.',
    'ஆபிரகாம் லிங்கனின் புகழ்பெற்ற சொற்றொடர் ஜனநாயகத்தை வரையறுக்கிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_091',
    'smp_2022_PAPER_II_SOC_SCI',
    'social_science',
    'ss_tamilnadu_history',
    91,
    '31',
    'Which Sangam age Tamil kingdom was known for the port city of Musiri (Muziris)?',
    'முசிறி துறைமுக நகருக்கு பெயர் பெற்ற சங்க கால தமிழ் அரசு எது?',
    'Chera', 'சேரர்',
    'Chola', 'சோழர்',
    'Pandya', 'பாண்டியர்',
    'Pallava', 'பல்லவர்',
    0,
    'medium',
    'factual',
    'The Cheras ruled the region west of the Western Ghats including the Musiri (Muziris) port.',
    'சேரர்கள் மேற்கு தொடர்ச்சி மலைக்கு மேற்கே முசிறி துறைமுகம் உட்பட பகுதியை ஆண்டனர்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_092',
    'smp_2019_PAPER_II_SOC_SCI',
    'social_science',
    'ss_indian_economy',
    92,
    '36',
    'The primary sector of the Indian economy mainly involves:',
    'இந்திய பொருளாதாரத்தின் முதன்மைத் துறை முக்கியமாக ஈடுபடுவது:',
    'Agriculture and raw material extraction', 'விவசாயம் மற்றும் மூலப்பொருள் பிரித்தெடுத்தல்',
    'Manufacturing goods', 'பொருட்கள் உற்பத்தி',
    'Banking services', 'வங்கி சேவைகள்',
    'Information technology', 'தகவல் தொழில்நுட்பம்',
    0,
    'easy',
    'conceptual',
    'Agriculture and raw material extraction form the primary sector.',
    'விவசாயம் மற்றும் மூலப்பொருள் பிரித்தெடுத்தல் முதன்மைத் துறையை உருவாக்குகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_093',
    'smp_2022_PAPER_II_SOC_SCI',
    'social_science',
    'ss_local_govt',
    93,
    '40',
    'Which constitutional amendment gave constitutional status to Panchayati Raj institutions?',
    'பஞ்சாயத்து ராஜ் நிறுவனங்களுக்கு அரசியலமைப்பு அந்தஸ்து அளித்த திருத்தம் எது?',
    '73rd Amendment', '73வது திருத்தம்',
    '42nd Amendment', '42வது திருத்தம்',
    '44th Amendment', '44வது திருத்தம்',
    '86th Amendment', '86வது திருத்தம்',
    0,
    'hard',
    'factual',
    'The 73rd Constitutional Amendment (1992) gave constitutional status to Panchayati Raj.',
    '73வது அரசியலமைப்பு திருத்தம் (1992) பஞ்சாயத்து ராஜுக்கு அரசியலமைப்பு அந்தஸ்து அளித்தது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_094',
    'smp_2019_PAPER_II_SOC_SCI',
    'social_science',
    'ss_ancient_india',
    94,
    '44',
    'Which Harappan site is known as the "Manchester of the ancient world" for cotton trade?',
    'பருத்தி வர்த்தகத்திற்கு "பண்டைய உலகின் மான்செஸ்டர்" என அழைக்கப்படும் ஹரப்பன் தளம் எது?',
    'Lothal', 'லோதல்',
    'Mohenjo-daro', 'மொஹஞ்சதாரோ',
    'Harappa', 'ஹரப்பா',
    'Kalibangan', 'காளிபங்கன்',
    0,
    'hard',
    'factual',
    'Lothal, a Harappan port, was renowned for its cotton trade and dockyard.',
    'லோதல், ஒரு ஹரப்பன் துறைமுகம், பருத்தி வர்த்தகம் மற்றும் கப்பல்துறைக்கு புகழ்பெற்றது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_095',
    'smp_2022_PAPER_II_SOC_SCI',
    'social_science',
    'ss_medieval_modern',
    95,
    '48',
    'The Revolt of 1857 is also known as:',
    '1857 இன் கிளர்ச்சி என்ன அழைக்கப்படுகிறது?',
    'India''s First War of Independence', 'இந்தியாவின் முதல் சுதந்திரப் போர்',
    'The Partition of Bengal', 'வங்க பிரிவினை',
    'The Salt March', 'உப்பு சத்தியாகிரகம்',
    'The Quit India Movement', 'வெள்ளையனே வெளியேறு இயக்கம்',
    0,
    'easy',
    'factual',
    'The Revolt of 1857 is often called India''s First War of Independence.',
    '1857 இன் கிளர்ச்சி இந்தியாவின் முதல் சுதந்திரப் போர் என அழைக்கப்படுகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_096',
    'smp_2019_PAPER_II_SOC_SCI',
    'social_science',
    'ss_tamilnadu_history',
    96,
    '53',
    'Which Chola ruler built the Brihadeeswarar Temple at Thanjavur?',
    'தஞ்சையில் பிரகதீஸ்வரர் கோவிலை கட்டிய சோழ மன்னன் யார்?',
    'Raja Raja Chola I', 'முதலாம் ராஜராஜ சோழன்',
    'Rajendra Chola I', 'முதலாம் ராஜேந்திர சோழன்',
    'Karikala Chola', 'கரிகால சோழன்',
    'Kulothunga Chola', 'குலோத்துங்க சோழன்',
    0,
    'medium',
    'factual',
    'Raja Raja Chola I built the Brihadeeswarar Temple at Thanjavur (c. 1010 CE).',
    'முதலாம் ராஜராஜ சோழன் தஞ்சை பிரகதீஸ்வரர் கோவிலை கட்டினார் (கி.பி. 1010).',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_097',
    'smp_2022_PAPER_II_SOC_SCI',
    'social_science',
    'ss_physio_india',
    97,
    '57',
    'The Deccan Plateau lies between which two ranges in India?',
    'தக்காண பீடபூமி இந்தியாவில் எந்த இரண்டு மலைத்தொடர்களுக்கு இடையில் உள்ளது?',
    'Western and Eastern Ghats', 'மேற்கு மற்றும் கிழக்கு தொடர்ச்சி மலைகள்',
    'Himalayas and Aravalli', 'இமயம் மற்றும் அரவள்ளி',
    'Vindhya and Satpura', 'விந்தியா மற்றும் சத்புரா',
    'Nilgiri and Annamalai', 'நீலகிரி மற்றும் அண்ணாமலை',
    0,
    'medium',
    'factual',
    'The Deccan Plateau is bounded by the Western and Eastern Ghats.',
    'தக்காண பீடபூமி மேற்கு மற்றும் கிழக்கு தொடர்ச்சி மலைகளால் எல்லைப்படுத்தப்படுகிறது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_098',
    'smp_2019_PAPER_II_SOC_SCI',
    'social_science',
    'ss_democracy',
    98,
    '60',
    'The fundamental right that allows citizens to move freely throughout the country is the right to:',
    'குடிமக்கள் நாடு முழுவதும் சுதந்திரமாக செல்ல அனுமதிக்கும் அடிப்படை உரிமை எது?',
    'Freedom of movement', 'நடமாடும் சுதந்திரம்',
    'Freedom of speech', 'பேச்சு சுதந்திரம்',
    'Freedom of religion', 'மத சுதந்திரம்',
    'Right to property', 'சொத்து உரிமை',
    0,
    'easy',
    'factual',
    'Freedom of movement is a fundamental right under Article 19 of the Constitution.',
    'நடமாடும் சுதந்திரம் அரசியலமைப்பின் சரத்து 19-இன் கீழ் அடிப்படை உரிமை.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  ),
  (
    'q_sample_099',
    'smp_2022_PAPER_II_SOC_SCI',
    'social_science',
    'ss_indian_economy',
    99,
    '63',
    'The 1991 economic reforms in India are most closely associated with the policy of:',
    'இந்தியாவில் 1991 பொருளாதார சீர்திருத்தங்கள் எந்த கொள்கையுடன் மிக நெருக்கமாக தொடர்புடையவை?',
    'Liberalisation and privatisation', 'தாராளமயமாக்கல் மற்றும் தனியார்மயமாக்கல்',
    'Total nationalisation', 'முழு தேசியமயமாக்கல்',
    'Import substitution', 'இறக்குமதி மாற்றீடு',
    'Closing foreign trade', 'வெளிநாட்டு வர்த்தகம் மூடுதல்',
    0,
    'medium',
    'factual',
    'The 1991 reforms introduced liberalisation, privatisation and globalisation (LPG).',
    '1991 சீர்திருத்தங்கள் தாராளமயமாக்கல், தனியார்மயமாக்கல் மற்றும் உலகமயமாக்கலை (LPG) அறிமுகப்படுத்தியது.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2022,
    true
  ),
  (
    'q_sample_100',
    'smp_2019_PAPER_II_SOC_SCI',
    'social_science',
    'ss_local_govt',
    100,
    '66',
    'The head of a Panchayat at the village level is called the:',
    'கிராம அளவில் பஞ்சாயத்தின் தலைவர் என அழைக்கப்படுகிறார்:',
    'Sarpanch', 'சர்பஞ்ச்',
    'Mayor', 'மேயர்',
    'Collector', 'கலெக்டர்',
    'Minister', 'அமைச்சர்',
    0,
    'easy',
    'factual',
    'The Sarpanch heads the village-level gram panchayat.',
    'சர்பஞ்ச் கிராம அளவிலான கிராம பஞ்சாயத்தை வழிநடத்துகிறார்.',
    NULL, NULL,
    'TRB TNTET Official Sample',
    2019,
    true
  )

ON CONFLICT (id) DO UPDATE SET
  paper_id = EXCLUDED.paper_id,
  subject_id = EXCLUDED.subject_id,
  topic_id = EXCLUDED.topic_id,
  question_en = EXCLUDED.question_en,
  question_ta = EXCLUDED.question_ta,
  correct_option = EXCLUDED.correct_option,
  difficulty = EXCLUDED.difficulty,
  question_type = EXCLUDED.question_type,
  year = EXCLUDED.year,
  is_active = EXCLUDED.is_active;

-- 3) question_topics mapping (primary topic link per question)
INSERT INTO public.question_topics (question_id, topic_id, is_primary, relevance_score) VALUES
  ('q_sample_001', 'cdp_physical_growth', true, 1.00),
  ('q_sample_002', 'cdp_learning_types', true, 1.00),
  ('q_sample_003', 'cdp_inclusive', true, 1.00),
  ('q_sample_004', 'cdp_constructivist', true, 1.00),
  ('q_sample_005', 'cdp_evaluation', true, 1.00),
  ('q_sample_006', 'cdp_p2_piaget_bruner', true, 1.00),
  ('q_sample_007', 'cdp_p2_memory', true, 1.00),
  ('q_sample_008', 'cdp_p2_motivation', true, 1.00),
  ('q_sample_009', 'cdp_p2_guidance', true, 1.00),
  ('q_sample_010', 'cdp_p2_intelligence', true, 1.00),
  ('q_sample_011', 'cdp_p2_creativity', true, 1.00),
  ('q_sample_012', 'cdp_p2_social', true, 1.00),
  ('q_sample_013', 'cdp_p2_learning_theories', true, 1.00),
  ('q_sample_014', 'cdp_p2_group', true, 1.00),
  ('q_sample_015', 'cdp_p2_mental_health', true, 1.00),
  ('q_sample_016', 'tamil_read_letters', true, 1.00),
  ('q_sample_017', 'tamil_grammar', true, 1.00),
  ('q_sample_018', 'tamil_read_text', true, 1.00),
  ('q_sample_019', 'tamil_speak_conversation', true, 1.00),
  ('q_sample_020', 'tamil_vocab_building', true, 1.00),
  ('q_sample_021', 'tamil_listen_rhymes', true, 1.00),
  ('q_sample_022', 'tamil_p2_elakkanam', true, 1.00),
  ('q_sample_023', 'tamil_read_words', true, 1.00),
  ('q_sample_024', 'tamil_write_sentences', true, 1.00),
  ('q_sample_025', 'tamil_p2_sangam', true, 1.00),
  ('q_sample_026', 'tamil_write_letters', true, 1.00),
  ('q_sample_027', 'tamil_speak_narration', true, 1.00),
  ('q_sample_028', 'tamil_language_functions', true, 1.00),
  ('q_sample_029', 'tamil_speak_rhymes', true, 1.00),
  ('q_sample_030', 'tamil_p2_bakthi', true, 1.00),
  ('q_sample_031', 'eng_read_phonics', true, 1.00),
  ('q_sample_032', 'eng_write_grammar', true, 1.00),
  ('q_sample_033', 'eng_speak_communication', true, 1.00),
  ('q_sample_034', 'eng_read_comprehension', true, 1.00),
  ('q_sample_035', 'eng_write_words', true, 1.00),
  ('q_sample_036', 'eng_read_phonics', true, 1.00),
  ('q_sample_037', 'eng_speak_fluency', true, 1.00),
  ('q_sample_038', 'eng_write_grammar', true, 1.00),
  ('q_sample_039', 'eng_listen_stories', true, 1.00),
  ('q_sample_040', 'eng_read_comprehension', true, 1.00),
  ('q_sample_041', 'eng_write_grammar', true, 1.00),
  ('q_sample_042', 'eng_p2_grammar', true, 1.00),
  ('q_sample_043', 'eng_write_words', true, 1.00),
  ('q_sample_044', 'eng_read_phonics', true, 1.00),
  ('q_sample_045', 'maths_number_concept', true, 1.00),
  ('q_sample_046', 'maths_addition_subtraction', true, 1.00),
  ('q_sample_047', 'maths_multiplication', true, 1.00),
  ('q_sample_048', 'maths_fractions', true, 1.00),
  ('q_sample_049', 'maths_2d_shapes', true, 1.00),
  ('q_sample_050', 'maths_symmetry', true, 1.00),
  ('q_sample_051', 'maths_length_weight', true, 1.00),
  ('q_sample_052', 'maths_time', true, 1.00),
  ('q_sample_053', 'maths_money', true, 1.00),
  ('q_sample_054', 'maths_patterns', true, 1.00),
  ('q_sample_055', 'maths_data', true, 1.00),
  ('q_sample_056', 'maths_fractions', true, 1.00),
  ('q_sample_057', 'maths_length_weight', true, 1.00),
  ('q_sample_058', 'maths_number_concept', true, 1.00),
  ('q_sample_059', 'evs_plant_parts', true, 1.00),
  ('q_sample_060', 'evs_animal_habitat', true, 1.00),
  ('q_sample_061', 'evs_water', true, 1.00),
  ('q_sample_062', 'evs_air', true, 1.00),
  ('q_sample_063', 'evs_food', true, 1.00),
  ('q_sample_064', 'evs_body', true, 1.00),
  ('q_sample_065', 'evs_health', true, 1.00),
  ('q_sample_066', 'evs_matter', true, 1.00),
  ('q_sample_067', 'evs_energy', true, 1.00),
  ('q_sample_068', 'evs_small_creatures', true, 1.00),
  ('q_sample_069', 'evs_day_night', true, 1.00),
  ('q_sample_070', 'evs_family_community', true, 1.00),
  ('q_sample_071', 'evs_tamilnadu', true, 1.00),
  ('q_sample_072', 'evs_india', true, 1.00),
  ('q_sample_073', 'ms_real_numbers', true, 1.00),
  ('q_sample_074', 'ms_algebra', true, 1.00),
  ('q_sample_075', 'ms_lines_angles', true, 1.00),
  ('q_sample_076', 'ms_mensuration', true, 1.00),
  ('q_sample_077', 'ms_matter', true, 1.00),
  ('q_sample_078', 'ms_biology', true, 1.00),
  ('q_sample_079', 'ms_forces', true, 1.00),
  ('q_sample_080', 'ms_light_sound', true, 1.00),
  ('q_sample_081', 'ms_algebra', true, 1.00),
  ('q_sample_082', 'ms_mensuration', true, 1.00),
  ('q_sample_083', 'ms_biology', true, 1.00),
  ('q_sample_084', 'ms_forces', true, 1.00),
  ('q_sample_085', 'ms_real_numbers', true, 1.00),
  ('q_sample_086', 'ms_light_sound', true, 1.00),
  ('q_sample_087', 'ss_ancient_india', true, 1.00),
  ('q_sample_088', 'ss_physio_india', true, 1.00),
  ('q_sample_089', 'ss_medieval_modern', true, 1.00),
  ('q_sample_090', 'ss_democracy', true, 1.00),
  ('q_sample_091', 'ss_tamilnadu_history', true, 1.00),
  ('q_sample_092', 'ss_indian_economy', true, 1.00),
  ('q_sample_093', 'ss_local_govt', true, 1.00),
  ('q_sample_094', 'ss_ancient_india', true, 1.00),
  ('q_sample_095', 'ss_medieval_modern', true, 1.00),
  ('q_sample_096', 'ss_tamilnadu_history', true, 1.00),
  ('q_sample_097', 'ss_physio_india', true, 1.00),
  ('q_sample_098', 'ss_democracy', true, 1.00),
  ('q_sample_099', 'ss_indian_economy', true, 1.00),
  ('q_sample_100', 'ss_local_govt', true, 1.00)
ON CONFLICT (question_id, topic_id) DO UPDATE SET is_primary = EXCLUDED.is_primary, relevance_score = EXCLUDED.relevance_score;

-- DONE