// Sample TNTET question rows for the import pipeline.
// These are realistic TRB-style exam questions used to test the app end-to-end.
// Each row targets a real syllabus topic (referenced by topicId) so the row
// passes FK validation against the seeded syllabus_topics table.
//
// To replace with real data: erase these via the generated
// scripts/erase_sample_questions.sql (DELETE WHERE id LIKE 'q_sample_%'),
// then import your own rows through the import tool.

export interface SampleQuestionRow {
  paper: 'PAPER_I' | 'PAPER_II_MATH_SCI' | 'PAPER_II_SOC_SCI';
  subject: string;      // display subject name (mapped via mapExcelSubjectToId)
  subjectId: string;    // resolved SubjectId
  topicId: string;      // valid syllabus_topics.id
  year: number;
  questionNo: string;
  questionEn: string;
  questionTa: string;
  optionsEn: [string, string, string, string];
  optionsTa: [string, string, string, string];
  correctIndex: number; // 0-3
  difficulty: 'easy' | 'medium' | 'hard';
  questionType: 'conceptual' | 'factual' | 'application' | 'pedagogy';
  explanationEn: string;
  explanationTa: string;
}

// ---------------------------------------------------------------------------
// Subject metadata for the display mapping + paper association
// ---------------------------------------------------------------------------
export const SAMPLE_SUBJECTS = [
  { subjectId: 'cdp', paper: 'PAPER_I' },
  { subjectId: 'cdp', paper: 'PAPER_II_MATH_SCI' },
  { subjectId: 'tamil', paper: 'PAPER_I' },
  { subjectId: 'english', paper: 'PAPER_I' },
  { subjectId: 'maths', paper: 'PAPER_I' },
  { subjectId: 'evs', paper: 'PAPER_I' },
  { subjectId: 'maths_science', paper: 'PAPER_II_MATH_SCI' },
  { subjectId: 'social_science', paper: 'PAPER_II_SOC_SCI' },
] as const;

export const SUBJECT_DISPLAY: Record<string, string> = {
  cdp: 'Child Development & Pedagogy',
  tamil: 'Tamil',
  english: 'English',
  maths: 'Mathematics',
  evs: 'Environmental Studies',
  maths_science: 'Mathematics & Science',
  social_science: 'Social Science',
};

// ---------------------------------------------------------------------------
// CDP — Paper I (5 questions)
// ---------------------------------------------------------------------------
const cdpP1: SampleQuestionRow[] = [
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_physical_growth',
    year: 2022,
    questionNo: '12',
    questionEn: 'According to Piaget, which stage of cognitive development do children in the 2–7 age range typically reach?',
    questionTa: 'பியாஜே கூற்றுப்படி, 2–7 வயதுடைய குழந்தைகள் பொதுவாக எந்த அறிவாற்றல் வளர்ச்சி நிலையை அடைகின்றனர்?',
    optionsEn: ['Sensory-motor stage', 'Pre-operational stage', 'Concrete operational stage', 'Formal operational stage'],
    optionsTa: ['உணர்வு-மோட்டார் நிலை', 'முன்-செயல் நிலை', 'குறிப்பிட்ட செயல் நிலை', 'முறைசார் செயல் நிலை'],
    correctIndex: 1,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'Children aged 2–7 are in the pre-operational stage, where symbolic thinking and language develop but logical reasoning is limited.',
    explanationTa: '2–7 வயதுடைய குழந்தைகள் முன்-செயல் நிலையில் உள்ளனர், அங்கு குறியீட்டு சிந்தனை மற்றும் மொழி வளரும், ஆனால் தர்க்கரீதியான பகுத்தறிவு குறைவாக இருக்கும்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_learning_types',
    year: 2019,
    questionNo: '8',
    questionEn: 'Which of the following is an example of signal learning in Gagné\u0027s hierarchy of learning?',
    questionTa: 'கனேயின் கற்றல் படிநிலையில் பின்வருவனவற்றுள் எது சிக்னல் கற்றலுக்கு example?',
    optionsEn: ['Ringing a bell before feeding a dog', 'Solving a maths word problem', 'Memorizing a poem', 'Drawing a picture of a tree'],
    optionsTa: ['நாய்க்கு உணவு கொடுப்பதற்கு முன் மணி ஓசை', 'கணிதச் சிக்கலைத் தீர்ப்பது', 'கவிதையை மனப்பாடம் செய்வது', 'மரத்தின் படத்தை வரைவது'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'Signal learning, the simplest level in Gagné\u0027s hierarchy, is a conditioned (Pavlovian) response to a stimulus such as a bell or a warning.',
    explanationTa: 'கனேயின் படிநிலையில் எளிமையான நிலையான சிக்னல் கற்றல், மணி அல்லது எச்சரிக்கை போன்ற தூண்டுதலுக்கான (பாவ்லோவிய) நிபந்தனைப் பதில்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_inclusive',
    year: 2022,
    questionNo: '27',
    questionEn: 'In an inclusive classroom, the most appropriate first step for a teacher noticing a student with a suspected specific learning disability is to:',
    questionTa: 'உள்ளடக்கிய வகுப்பறையில், குறிப்பிட்ட கற்றல் குறைபாடு இருப்பதாகக் கருதப்படும் மாணவரைக் கவனிக்கும் ஆசிரியர் எடுக்க வேண்டிய மிகச் சரியான முதல் படி:',
    optionsEn: ['Refer the child for assessment and adapt teaching', 'Ignore the difficulty to avoid embarrassment', 'Move the child to a lower class', 'Discipline the child for not studying'],
    optionsTa: ['குழந்தையை மதிப்பீட்டுக்கு அனுப்பி கற்பித்தலை மாற்றியமைத்தல்', 'சங்கடத்தைத் தவிர்க்க கஷ்டத்தை புறக்கணித்தல்', 'குழந்தையை குறைந்த வகுப்புக்கு மாற்றுதல்', 'படிக்காததற்காக குழந்தையை தண்டித்தல்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'pedagogy',
    explanationEn: 'An inclusive teacher first responds to concerns by seeking formal assessment and then adapting instruction to meet the child\u0027s needs.',
    explanationTa: 'உள்ளடக்கிய ஆசிரியர் முதலில் முறையான மதிப்பீட்டை நாடி, பின்னர் குழந்தையின் தேவைகளுக்கேற்ப கற்பித்தலை மாற்றியமைக்கிறார்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_constructivist',
    year: 2019,
    questionNo: '35',
    questionEn: 'A constructivist teacher would most likely encourage students to:',
    questionTa: 'கட்டமைப்பாளர் ஆசிரியர் மாணவர்களை எதைச் செய்ய ஊக்குவிப்பார்?',
    optionsEn: ['Build knowledge through hands-on experience and reflection', 'Only memorize textbook answers', 'Listen to long lectures passively', 'Copy notes from the blackboard'],
    optionsTa: ['கைகளால் செய்யும் அனுபவம் மற்றும் பிரதிபலிப்பு மூலம் அறிவை உருவாக்குதல்', 'பாடப்புத்தக பதில்களை மட்டும் மனப்பாடம் செய்தல்', 'நீண்ட விரிவுரைகளை செயலற்று கேட்டல்', 'பலகையிலிருந்து குறிப்புகளை நகலெடுத்தல்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'pedagogy',
    explanationEn: 'Constructivism holds that learners actively build understanding through experience, discovery, and reflection rather than passive reception.',
    explanationTa: 'கட்டமைப்பியல் கற்றவர்கள் செயலற்ற பெறுதல் அல்லாமல் அனுபவம், கண்டுபிடிப்பு மற்றும் பிரதிபலிப்பு மூலம் அறிவைத் தீவிரமாக உருவாக்குகின்றனர் என்று கூறுகிறது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_evaluation',
    year: 2022,
    questionNo: '44',
    questionEn: 'Continuous and Comprehensive Evaluation (CCE) in formative assessment primarily aims to:',
    questionTa: 'தொடர்ச்சியான மற்றும் விரிவான மதிப்பீடு (CCE) வடிவான மதிப்பீட்டில் முதன்மையாக எதை இலக்காகக் கொண்டுள்ளது?',
    optionsEn: ['Provide ongoing feedback to improve learning', 'Rank students in a single final exam', 'Award marks for attendance only', 'Compare one school with another'],
    optionsTa: ['கற்றலை மேம்படுத்த தொடர்ச்சியான கருத்தை வழங்குதல்', 'ஒரே இறுதித் தேர்வில் மாணவர்களை தரவரிசைப்படுத்துதல்', 'வருகைக்கு மட்டும் மதிப்பெண் வழங்குதல்', 'ஒரு பள்ளியை மற்றொன்றுடன் ஒப்பிடுதல்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'Formative/CCE assessment is designed to give continuous feedback that guides and improves learning throughout the course.',
    explanationTa: 'வடிவான CCE மதிப்பீடு பாடநெறி முழுவதும் கற்றலை மேம்படுத்தும் தொடர்ச்சியான கருத்தை வழங்க வடிவமைக்கப்பட்டுள்ளது.',
  },
];

// ---------------------------------------------------------------------------
// CDP — Paper II (4 questions)
// ---------------------------------------------------------------------------
const cdpP2: SampleQuestionRow[] = [
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_p2_piaget_bruner',
    year: 2022,
    questionNo: '15',
    questionEn: 'Jerome Bruner\u0027s concept of the "spiral curriculum" emphasizes that teaching should:',
    questionTa: 'ஜெரோம் ப்ரூனரின் "சுழல் பாடத்திட்டம்" கருத்து கற்பித்தல் என்னவாக இருக்க வேண்டும் என வலியுறுத்துகிறது?',
    optionsEn: ['Revisit topics at increasing levels of complexity', 'Teach each topic only once per year', 'Separate all subjects completely', 'Focus only on memorization'],
    optionsTa: ['அதிகரிக்கும் சிக்கலான நிலைகளில் தலைப்புகளை மீளாய்வு செய்தல்', 'ஒவ்வொரு தலைப்பையும் வருடத்திற்கு ஒருமுறை மட்டும் கற்பித்தல்', 'அனைத்து பாடங்களையும் முற்றிலும் பிரித்தல்', 'மனப்பாடத்தில் மட்டும் கவனம் செலுத்துதல்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'The spiral curriculum revisits fundamental ideas repeatedly, each time at a higher level of sophistication so learners deepen understanding.',
    explanationTa: 'சுழல் பாடத்திட்டம் அடிப்படை கருத்துக்களை மீண்டும் மீண்டும் அதிக நுட்பமான நிலைகளில் ஆராய்ந்து கற்றவர்களின் புரிதலை ஆழப்படுத்துகிறது.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_p2_memory',
    year: 2019,
    questionNo: '22',
    questionEn: 'Which memory process describes the act of bringing stored information back into conscious awareness?',
    questionTa: 'சேமித்த தகவல்களை உணர்வு நிலைக்கு மீண்டும் கொண்டுவரும் செயலை விவரிக்கும் நினைவாற்றல் செயல்முறை எது?',
    optionsEn: ['Retrieval', 'Encoding', 'Storage', 'Rehearsal'],
    optionsTa: ['மீட்டெடுப்பு', 'குறியாக்கம்', 'சேமிப்பு', 'மீள்சொல்லல்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'Retrieval is the process of accessing and bringing stored memories back into conscious awareness.',
    explanationTa: 'மீட்டெடுப்பு என்பது சேமித்த நினைவுகளை அணுகி உணர்வு நிலைக்கு மீண்டும் கொண்டுவரும் செயல்முறை.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_p2_motivation',
    year: 2022,
    questionNo: '30',
    questionEn: 'A student who studies hard because he genuinely enjoys learning is said to be ______ motivated.',
    questionTa: 'கற்றலை உண்மையாகவே விரும்புவதால் கடினமாக படிக்கும் மாணவர் ______ உந்துதலுடன் உள்ளார்.',
    optionsEn: ['Intrinsically', 'Extrinsically', 'Negatively', 'Externally'],
    optionsTa: ['உள்ளார்ந்த', 'வெளிப்புற', 'எதிர்மறை', 'வெளியிலிருந்து'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'Intrinsic motivation comes from internal enjoyment and interest in the activity itself, rather than external rewards.',
    explanationTa: 'உள்ளார்ந்த உந்துதல் வெளிப்புற வெகுமதிகளை விட செயலிலேயே உள்ள உள் மகிழ்ச்சி மற்றும் ஆர்வத்திலிருந்து வருகிறது.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_p2_guidance',
    year: 2019,
    questionNo: '40',
    questionEn: 'In school guidance, which type of counselling focuses on helping students understand and solve an immediate personal problem?',
    questionTa: 'பள்ளி வழிகாட்டலில், மாணவர்களுக்கு உடனடி தனிப்பட்ட சிக்கலைப் புரிந்துகொள்ளவும் தீர்க்கவும் உதவும் ஆலோசனை வகை எது?',
    optionsEn: ['Directive counseling', 'Non-directive counseling', 'Eclectic counseling', 'Vocational counseling'],
    optionsTa: ['வழிகாட்டும் ஆலோசனை', 'வழிகாட்டா ஆலோசனை', 'கலப்பு ஆலோசனை', 'தொழில் ஆலோசனை'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'factual',
    explanationEn: 'Directive (counsellor-centred) counselling guides a student toward solving an immediate, specific problem through structured advice.',
    explanationTa: 'வழிகாட்டும் (ஆலோசகர்-மைய) ஆலோசனை, கட்டமைக்கப்பட்ட ஆலோசனை மூலம் உடனடி, குறிப்பிட்ட சிக்கலைத் தீர்க்க மாணவரை வழிநடத்துகிறது.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_p2_intelligence',
    year: 2019,
    questionNo: '41',
    questionEn: 'Who developed the "Theory of Multiple Intelligences"?',
    questionTa: '"பன்மடங்கு நுண்ணறிவு கோட்பாட்டை" உருவாக்கியவர் யார்?',
    optionsEn: ['Howard Gardner', 'Charles Spearman', 'Alfred Binet', 'Jean Piaget'],
    optionsTa: ['ஹோவர்ட் கார்ட்னர்', 'சார்லஸ் ஸ்பியர்மேன்', 'ஆல்பிரட் பினே', 'ஜீன் பியாஜே'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'Howard Gardner proposed the theory of multiple intelligences (linguistic, logical, musical, spatial, etc.).',
    explanationTa: 'ஹோவர்ட் கார்ட்னர் பன்மடங்கு நுண்ணறிவு கோட்பாட்டை (மொழி, தர்க்கம், இசை, இடம் போன்றவை) முன்மொழிந்தார்.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_p2_creativity',
    year: 2022,
    questionNo: '43',
    questionEn: 'Divergent thinking is most closely associated with which ability?',
    questionTa: 'வேறுபட்ட சிந்தனை எந்த திறனுடன் மிக நெருக்கமாக தொடர்புடையது?',
    optionsEn: ['Creativity', 'Memory', 'Attention', 'Perception'],
    optionsTa: ['படைப்பாற்றல்', 'நினைவாற்றல்', 'கவனம்', 'உணர்தல்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'Divergent thinking, generating many novel ideas, is central to creativity.',
    explanationTa: 'பல புதிய கருத்துகளை உருவாக்கும் வேறுபட்ட சிந்தனை படைப்பாற்றலுக்கு மையமானது.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_p2_social',
    year: 2019,
    questionNo: '46',
    questionEn: 'According to Erikson, the psychosocial crisis of adolescence is:',
    questionTa: 'எரிக்சனின் கூற்றுப்படி, இளமைப் பருவத்தின் மனோசமூக நெருக்கடி எது?',
    optionsEn: ['Identity vs Role Confusion', 'Trust vs Mistrust', 'Initiative vs Guilt', 'Integrity vs Despair'],
    optionsTa: ['அடையாளம் vs பாத்திரக் குழப்பம்', 'நம்பிக்கை vs அவநம்பிக்கை', 'முயற்சி vs குற்றவுணர்வு', 'நேர்மை vs விரக்தி'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'factual',
    explanationEn: 'Erikson\u0027s adolescent stage is the crisis of Identity versus Role Confusion.',
    explanationTa: 'எரிக்சனின் இளமைப் பருவ நிலை, அடையாளம் எதிர் பாத்திரக் குழப்பம் நெருக்கடி.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_p2_learning_theories',
    year: 2022,
    questionNo: '49',
    questionEn: 'Operant conditioning, based on reinforcement and punishment, was proposed by:',
    questionTa: 'வலுவூட்டல் மற்றும் தண்டனையின் அடிப்படையிலான செயல்வினை நிபந்தனையை முன்மொழிந்தவர்:',
    optionsEn: ['B.F. Skinner', 'Ivan Pavlov', 'Edward Thorndike', 'Lev Vygotsky'],
    optionsTa: ['பி.எஃப். ஸ்கின்னர்', 'இவான் பாவ்லோவ்', 'எட்வர்ட் தார்ன்டைக்', 'லெவ் வைகாட்ஸ்கி'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'B.F. Skinner proposed operant conditioning using reinforcement and punishment.',
    explanationTa: 'பி.எஃப். ஸ்கின்னர் வலுவூட்டல் மற்றும் தண்டனையைப் பயன்படுத்தி செயல்வினை நிபந்தனையை முன்மொழிந்தார்.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_p2_group',
    year: 2019,
    questionNo: '51',
    questionEn: 'The tendency to perform better on simple tasks in the presence of others is called:',
    questionTa: 'மற்றவர்கள் முன்னிலையில் எளிய பணிகளில் சிறப்பாக செயல்படும் போக்கு என அழைக்கப்படுகிறது:',
    optionsEn: ['Social facilitation', 'Social loafing', 'Group conformity', 'Deindividuation'],
    optionsTa: ['சமூக வசதி', 'சமூக சோம்பல்', 'குழு ஒத்திசைவு', 'தனித்துவ இழப்பு'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'conceptual',
    explanationEn: 'Social facilitation is the improved performance on simple/well-learned tasks in the presence of others.',
    explanationTa: 'சமூக வசதி என்பது மற்றவர்கள் முன்னிலையில் எளிய/நன்கு கற்ற பணிகளில் மேம்பட்ட செயல்திறன்.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.cdp,
    subjectId: 'cdp',
    topicId: 'cdp_p2_mental_health',
    year: 2022,
    questionNo: '54',
    questionEn: 'Which vitamin deficiency is commonly linked to fatigue and weakness in students?',
    questionTa: 'மாணவர்களுக்கு சோர்வு மற்றும் பலவீனத்துடன் பொதுவாக தொடர்புடைய வைட்டமின் குறைபாடு எது?',
    optionsEn: ['Vitamin B12 / Iron', 'Vitamin C', 'Vitamin A', 'Vitamin D only'],
    optionsTa: ['வைட்டமின் B12 / இரும்பு', 'வைட்டமின் C', 'வைட்டமின் A', 'வைட்டமின் D மட்டும்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'Vitamin B12 and iron deficiency are common causes of fatigue and weakness.',
    explanationTa: 'வைட்டமின் B12 மற்றும் இரும்பு குறைபாடு சோர்வு மற்றும் பலவீனத்தின் பொதுவான காரணங்கள்.',
  },
];

// ---------------------------------------------------------------------------
// Tamil — Paper I (14 questions)
// Let's author a compact but representative set.
// ---------------------------------------------------------------------------
const tamilP1: SampleQuestionRow[] = [
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_read_letters',
    year: 2022,
    questionNo: '3',
    questionEn: 'Which of the following is a Mei (consonant) letter in Tamil?',
    questionTa: 'பின்வருவனவற்றில் எது தமிழில் மெய் (மெய்யெழுத்து)?',
    optionsEn: ['க', 'அ', 'ஆ', 'இ'],
    optionsTa: ['க', 'அ', 'ஆ', 'இ'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'க is a Mei (consonant) letter; அ, ஆ, இ are Uyir (vowel) letters in Tamil.',
    explanationTa: 'க என்பது மெய் (மெய்யெழுத்து); அ, ஆ, இ ஆகியவை உயிர் (உயிரெழுத்து) எழுத்துகள்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_grammar',
    year: 2019,
    questionNo: '7',
    questionEn: 'How many "Uyirmei" (compound) letters are there in Tamil?',
    questionTa: 'தமிழில் எத்தனை "உயிர்மெய்" (சேர்ம) எழுத்துகள் உள்ளன?',
    optionsEn: ['216', '12', '18', '247'],
    optionsTa: ['216', '12', '18', '247'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'Tamil has 12 Uyir and 18 Mei letters; their 216 combinations form the Uyirmei letters (12 × 18).',
    explanationTa: 'தமிழில் 12 உயிர் மற்றும் 18 மெய் எழுத்துகள்; அவற்றின் 216 சேர்க்கைகள் உயிர்மெய் எழுத்துகளை உருவாக்குகின்றன (12 × 18).',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_read_text',
    year: 2022,
    questionNo: '11',
    questionEn: 'Which Tamil literary text is written entirely in "Asaariappaa" (ஆசிரியப்பா) metre?',
    questionTa: 'எந்த தமிழ் இலக்கிய நூல் முழுவதும் "ஆசிரியப்பா" வகை யாப்பில் எழுதப்பட்டது?',
    optionsEn: ['Thirukkural', 'Tolkappiyam', 'Silappathikaram', 'Nannool'],
    optionsTa: ['திருக்குறள்', 'தொல்காப்பியம்', 'சிலப்பதிகாரம்', 'நன்னூல்'],
    correctIndex: 2,
    difficulty: 'hard',
    questionType: 'factual',
    explanationEn: 'Silappathikaram, one of the five great epics, is composed in the Asaariappaa metre throughout.',
    explanationTa: 'ஐம்பெரும் காப்பியங்களில் ஒன்றான சிலப்பதிகாரம் முழுவதும் ஆசிரியப்பா யாப்பில் இயற்றப்பட்டது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_speak_conversation',
    year: 2019,
    questionNo: '19',
    questionEn: 'The polite form of address used for a teacher in Tamil is:',
    questionTa: 'ஆசிரியருக்கு தமிழில் பயன்படுத்தப்படும் மரியாதையான அழைப்பு வடிவம்:',
    optionsEn: ['தங்கள்', 'நீங்கள்', 'நீ', 'அவர்'],
    optionsTa: ['தங்கள்', 'நீங்கள்', 'நீ', 'அவர்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: '"தங்கள்" is the most respectful/polite form of address in Tamil.',
    explanationTa: '"தங்கள்" என்பது தமிழில் மிகவும் மரியாதையான அழைப்பு வடிவம்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_vocab_building',
    year: 2022,
    questionNo: '23',
    questionEn: 'Choose the correct antonym for the word "நாட்கள்" (days) in the sense of "வீழ்ச்சி" (decline):',
    questionTa: '"வீழ்ச்சி" (decline) என்பதன் எதிர்ச்சொல்லைத் தேர்ந்தெடுக்கவும்:',
    optionsEn: ['உயர்வு', 'சரிவு', 'இறக்கம்', 'அழிவு'],
    optionsTa: ['உயர்வு', 'சரிவு', 'இறக்கம்', 'அழிவு'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'உயர்வு (rise) is the antonym of வீழ்ச்சி (fall/decline).',
    explanationTa: 'வீழ்ச்சியின் எதிர்ச்சொல் உயர்வு.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_listen_rhymes',
    year: 2019,
    questionNo: '26',
    questionEn: 'Which famous Tamil poet wrote the "Neethi Neri Vilakkam" emphasising moral conduct?',
    questionTa: 'நீதி நெறி விளக்கம் எழுதிய புகழ்பெற்ற தமிழ் கவிஞர் யார் (நற்பொருள் நடத்தையை வலியுறுத்தியது)?',
    optionsEn: ['Auvaiyar', 'Kambar', 'Ilango Adigal', 'Thiruvalluvar'],
    optionsTa: ['ஔவையார்', 'கம்பர்', 'இளங்கோ அடிகள்', 'திருவள்ளுவர்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'Auvaiyar\u0027s Neethi Neri Vilakkam is a celebrated Tamil didactic work on moral conduct.',
    explanationTa: 'ஔவையாரின் நீதி நெறி விளக்கம், நற்பொருள் நடத்தை பற்றிய புகழ்பெற்ற தமிழ் நீதிநூல்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_p2_elakkanam',
    year: 2022,
    questionNo: '31',
    questionEn: 'In Tamil grammar, "எழுத்து" refers to which of the following?',
    questionTa: 'தமிழ் இலக்கணத்தில் "எழுத்து" பின்வருவனவற்றில் எதைக் குறிக்கிறது?',
    optionsEn: ['Letters/alphabets', 'Words', 'Sentences', 'Meanings'],
    optionsTa: ['எழுத்துகள்', 'சொற்கள்', 'வாக்கியங்கள்', 'பொருள்கள்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'எழுத்து (letters) is the first of the three divisions in Tamil grammar (எழுத்து, சொல், பொருள்).',
    explanationTa: 'தமிழ் இலக்கணத்தின் மூன்று பிரிவுகளில் (எழுத்து, சொல், பொருள்) எழுத்து முதலாவது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_read_words',
    year: 2019,
    questionNo: '36',
    questionEn: 'What is the correct Tamil word for the number 30?',
    questionTa: '30 என்ற எண்ணுக்கு சரியான தமிழ்ச் சொல் எது?',
    optionsEn: ['முப்பது', 'முன்று', 'இருபது', 'நாற்பது'],
    optionsTa: ['முப்பது', 'முன்று', 'இருபது', 'நாற்பது'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'முப்பது is the Tamil word for the number thirty (30).',
    explanationTa: 'முப்பது என்பது 30 என்ற எண்ணுக்கான தமிழ்ச்சொல்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_write_sentences',
    year: 2022,
    questionNo: '41',
    questionEn: 'Identify the correct Tamil sentence structure for "The boy is reading a book":',
    questionTa: '"The boy is reading a book" என்பதற்கான சரியான தமிழ் வாக்கிய அமைப்பை அடையாளம் காணவும்:',
    optionsEn: ['சிறுவன் புத்தகம் படிக்கிறான்', 'புத்தகம் சிறுவன் படிக்கிறான்', 'சிறுவன் படிக்கிறான் புத்தகம்', 'படிக்கிறான் புத்தகம் சிறுவன்'],
    optionsTa: ['சிறுவன் புத்தகம் படிக்கிறான்', 'புத்தகம் சிறுவன் படிக்கிறான்', 'சிறுவன் படிக்கிறான் புத்தகம்', 'படிக்கிறான் புத்தகம் சிறுவன்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'Tamil follows the SOV order: subject (சிறுவன்), object (புத்தகம்), verb (படிக்கிறான்).',
    explanationTa: 'தமிழ் SOV வரிசையைப் பின்பற்றுகிறது: செய்பவர் (சிறுவன்), செயப்படுபொருள் (புத்தகம்), வினை (படிக்கிறான்).',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_p2_sangam',
    year: 2019,
    questionNo: '47',
    questionEn: '"Tholkappiyam", the oldest extant Tamil grammar, was written by whom?',
    questionTa: 'தொல்காப்பியம், தொன்மையான தமிழ் இலக்கணம், யாரால் எழுதப்பட்டது?',
    optionsEn: ['Tholkappiyar', 'Nannoolar', 'Auvaiyar', 'Kambar'],
    optionsTa: ['தொல்காப்பியர்', 'நன்னூலர்', 'ஔவையார்', 'கம்பர்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'Tholkappiyam, the oldest Tamil grammar, is attributed to Tholkappiyar.',
    explanationTa: 'தொல்காப்பியம், தொன்மையான தமிழ் இலக்கணம், தொல்காப்பியரால் இயற்றப்பட்டது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_write_letters',
    year: 2022,
    questionNo: '50',
    questionEn: 'Which of these is a "Kuril" (short) Uyir vowel in Tamil?',
    questionTa: 'இவற்றில் எது தமிழில் "குறில்" (குறுகிய) உயிர் எழுத்து?',
    optionsEn: ['அ', 'ஆ', 'ஈ', 'ஊ'],
    optionsTa: ['அ', 'ஆ', 'ஈ', 'ஊ'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'அ is a short (Kuril) vowel; ஆ, ஈ, ஊ are long (Nedil) vowels.',
    explanationTa: 'அ குறில் (குறுகிய) உயிர்; ஆ, ஈ, ஊ நெடில் (நீண்ட) உயிர்கள்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_speak_narration',
    year: 2019,
    questionNo: '55',
    questionEn: 'Which Tamil literary genre was used to compose "Tirumurai" (devotional hymns)?',
    questionTa: 'எந்த தமிழ் இலக்கிய வகையில் "திருமுறை" (பக்தி இசைகள்) இயற்றப்பட்டது?',
    optionsEn: ['Pathigam', 'Kappiyam', 'Purananuru', 'Akananuru'],
    optionsTa: ['பதிகம்', 'காப்பியம்', 'புறநானூறு', 'அகநானூறு'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'factual',
    explanationEn: 'The Tirumurai devotional hymns were composed in the Pathigam genre by the Nayanmars.',
    explanationTa: 'திருமுறை பக்தி இசைகள் நாயன்மார்களால் பதிகம் வகையில் இயற்றப்பட்டது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_language_functions',
    year: 2022,
    questionNo: '60',
    questionEn: 'The word "ஆயின்" (if) is used in Tamil to express which function?',
    questionTa: '"ஆயின்" (if) என்ற சொல் தமிழில் எந்த செயல்பாட்டை வெளிப்படுத்தப் பயன்படுகிறது?',
    optionsEn: ['Condition', 'Exclamation', 'Question', 'Command'],
    optionsTa: ['நிபந்தனை', 'வியப்பு', 'வினா', 'கட்டளை'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'ஆயின் marks a conditional/if-then relationship in Tamil.',
    explanationTa: 'ஆயின் தமிழில் நிபந்தனை/என்றால் உறவைக் குறிக்கிறது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_speak_rhymes',
    year: 2019,
    questionNo: '64',
    questionEn: 'Which of the following is a Tamil tongue-twister (சொற்புரட்டு)?',
    questionTa: 'பின்வருவனவற்றில் எது தமிழ் சொற்புரட்டு?',
    optionsEn: ['காக்கை கருகருத்து', 'வானம் பூமி', 'யானை மலை', 'மீன் நீர்'],
    optionsTa: ['காக்கை கருகருத்து', 'வானம் பூமி', 'யானை மலை', 'மீன் நீர்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: '"காக்கை கருகருத்து" is a well-known Tamil tongue-twister.',
    explanationTa: '"காக்கை கருகருத்து" பிரபலமான தமிழ் சொற்புரட்டு.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.tamil,
    subjectId: 'tamil',
    topicId: 'tamil_p2_bakthi',
    year: 2022,
    questionNo: '65',
    questionEn: 'Which Tamil saint, known for his Devaram hymns, is counted among the Nayanmars?',
    questionTa: 'தேவார இசைகளுக்கு பெயர் பெற்ற, நாயன்மார்களில் கணக்கிடப்படும் தமிழ் சமயத் துறவி யார்?',
    optionsEn: ['Appar', 'Auvaiyar', 'Kambar', 'Thiruvalluvar'],
    optionsTa: ['அப்பர்', 'ஔவையார்', 'கம்பர்', 'திருவள்ளுவர்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'Appar (Thirunavukkarasar), a Nayanmar, composed Devaram hymns.',
    explanationTa: 'அப்பர் (திருநாவுக்கரசர்), ஒரு நாயன்மார், தேவார இசைகளை இயற்றினார்.',
  },
];

// ---------------------------------------------------------------------------
// English — Paper I (14 questions)
// ---------------------------------------------------------------------------
const englishP1: SampleQuestionRow[] = [
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_read_phonics',
    year: 2022,
    questionNo: '5',
    questionEn: 'Which of the following words has a short /a/ vowel sound as in "cat"?',
    questionTa: '"cat" என்பதில் உள்ளது போன்ற குறுகிய /a/ உயிர் ஒலி கொண்ட வார்த்தை எது?',
    optionsEn: ['hat', 'hate', 'cake', 'late'],
    optionsTa: ['hat', 'hate', 'cake', 'late'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: '"hat" has a short /a/ sound; the others contain a long /eɪ/ sound.',
    explanationTa: '"hat" குறுகிய /a/ ஒலி கொண்டது; மற்றவை நீண்ட /eɪ/ ஒலி கொண்டவை.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_write_grammar',
    year: 2019,
    questionNo: '9',
    questionEn: 'Choose the correct plural form of the noun "child":',
    questionTa: '"child" என்ற பெயர்ச்சொல்லின் சரியான பன்மை வடிவத்தைத் தேர்ந்தெடுக்கவும்:',
    optionsEn: ['children', 'childs', 'childes', 'children'],
    optionsTa: ['children', 'childs', 'childes', 'children'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: '"children" is the irregular plural form of "child".',
    explanationTa: '"children" என்பது "child" இன் முறையற்ற பன்மை வடிவம்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_speak_communication',
    year: 2022,
    questionNo: '13',
    questionEn: 'Which of the following is an appropriate way to greet a teacher in the morning in English?',
    questionTa: 'காலையில் ஆங்கிலத்தில் ஆசிரியரை வாழ்த்துவதற்கான சரியான வழி எது?',
    optionsEn: ['Good morning, Sir/Madam', 'Hey, you', 'What\u0027s up, teacher?', 'Yo, bro'],
    optionsTa: ['Good morning, Sir/Madam', 'Hey, you', 'What\u0027s up, teacher?', 'Yo, bro'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: '"Good morning, Sir/Madam" is a polite and respectful formal greeting.',
    explanationTa: '"Good morning, Sir/Madam" என்பது மரியாதையான முறையான வாழ்த்து.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_read_comprehension',
    year: 2019,
    questionNo: '17',
    questionEn: 'In the sentence "The lazy cat slept all day", the word "lazy" is which part of speech?',
    questionTa: '"The lazy cat slept all day" என்ற வாக்கியத்தில் "lazy" என்ற சொல் எந்த இலக்கண உறுப்பு?',
    optionsEn: ['Adjective', 'Verb', 'Adverb', 'Noun'],
    optionsTa: ['வினை', 'பெயர்ச்சொல்', 'உரிச்சொல்', 'வினையுரிச்சொல்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: '"lazy" describes the noun "cat", so it is an adjective.',
    explanationTa: '"lazy" "cat" என்ற பெயர்ச்சொல்லை விவரிக்கிறது, எனவே இது பெயரடை.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_write_words',
    year: 2022,
    questionNo: '21',
    questionEn: 'What is the antonym of the word "generous"?',
    questionTa: '"generous" என்ற வார்த்தையின் எதிர்ச்சொல் எது?',
    optionsEn: ['stingy', 'kind', 'helpful', 'friendly'],
    optionsTa: ['stingy', 'kind', 'helpful', 'friendly'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: '"stingy" (miserly/unwilling to give) is the opposite of "generous".',
    explanationTa: '"stingy" (கஞ்சத்தனமான) "generous" இன் எதிர்ச்சொல்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_read_phonics',
    year: 2019,
    questionNo: '25',
    questionEn: 'Which letter combination represents the sound /ʃ/ as in "ship"?',
    questionTa: '"ship" இல் உள்ள /ʃ/ ஒலியைக் குறிக்கும் எழுத்துக் கூட்டம் எது?',
    optionsEn: ['sh', 'ch', 'th', 'ph'],
    optionsTa: ['sh', 'ch', 'th', 'ph'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'The digraph "sh" represents the /ʃ/ sound.',
    explanationTa: '"sh" என்ற இருமை எழுத்து /ʃ/ ஒலியைக் குறிக்கிறது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_speak_fluency',
    year: 2022,
    questionNo: '29',
    questionEn: 'Which sentence uses correct subject-verb agreement?',
    questionTa: 'எந்த வாக்கியம் சரியான செய்பவர்-வினை பொருத்தத்தைப் பயன்படுத்துகிறது?',
    optionsEn: ['She goes to school daily.', 'She go to school daily.', 'She going to school daily.', 'She gone to school daily.'],
    optionsTa: ['She goes to school daily.', 'She go to school daily.', 'She going to school daily.', 'She gone to school daily.'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'The third-person singular subject "She" requires the verb form "goes".',
    explanationTa: 'மூன்றாம் நபர் ஒருமை செய்பவர் "She" க்கு "goes" என்ற வினை வடிவம் தேவை.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_write_grammar',
    year: 2019,
    questionNo: '32',
    questionEn: 'Identify the preposition in the sentence: "The book is on the table."',
    questionTa: '"The book is on the table." என்ற வாக்கியத்தில் முன்விபக்தியை அடையாளம் காணவும்.',
    optionsEn: ['on', 'the', 'book', 'is'],
    optionsTa: ['on', 'the', 'book', 'is'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: '"on" shows the relationship between the book and the table, so it is a preposition.',
    explanationTa: '"on" புத்தகத்திற்கும் மேசைக்கும் இடையிலான உறவைக் காட்டுகிறது, எனவே இது முன்விபக்தி.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_listen_stories',
    year: 2022,
    questionNo: '37',
    questionEn: 'Which of the following is a common element of a fable?',
    questionTa: 'பின்வருவனவற்றில் எது நீதிக்கதையின் (fable) பொதுவான அம்சம்?',
    optionsEn: ['Talking animals with a moral', 'Only human characters', 'No lesson at the end', 'Always set in a city'],
    optionsTa: ['ஒழுக்கத்துடன் பேசும் விலங்குகள்', 'மனித கதாபாத்திரங்கள் மட்டும்', 'இறுதியில் பாடமில்லை', 'எப்போதும் நகரில் அமைந்தவை'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'Fables typically feature talking animals and end with a moral lesson.',
    explanationTa: 'நீதிக்கதைகள் பொதுவாக பேசும் விலங்குகளைக் கொண்டு ஒழுக்கப் பாடத்துடன் முடிகின்றன.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_read_comprehension',
    year: 2019,
    questionNo: '42',
    questionEn: 'The main idea of a passage is best defined as:',
    questionTa: 'ஒரு பத்தியின் முக்கிய கருத்து எவ்வாறு வரையறுக்கப்படுகிறது?',
    optionsEn: ['The central point the author wants to convey', 'The first sentence only', 'The list of all details', 'The title of the book'],
    optionsTa: ['ஆசிரியர் தெரிவிக்க விரும்பும் மையக் கருத்து', 'முதல் வாக்கியம் மட்டும்', 'அனைத்து விவரங்களின் பட்டியல்', 'புத்தகத்தின் தலைப்பு'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'The main idea is the central, most important point an author conveys about the topic.',
    explanationTa: 'முக்கிய கருத்து என்பது ஆசிரியர் தலைப்பைப் பற்றி தெரிவிக்கும் மைய, மிக முக்கியமான புள்ளி.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_write_grammar',
    year: 2022,
    questionNo: '46',
    questionEn: 'Which word is a conjunction in: "Ravi studied hard, so he passed the exam."?',
    questionTa: '"Ravi studied hard, so he passed the exam." என்பதில் எது இணைப்புச்சொல்?',
    optionsEn: ['so', 'hard', 'exam', 'passed'],
    optionsTa: ['so', 'hard', 'exam', 'passed'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: '"so" connects the two clauses, so it is a conjunction.',
    explanationTa: '"so" இரண்டு உட்கூறுகளை இணைக்கிறது, எனவே இது இணைப்புச்சொல்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_p2_grammar',
    year: 2019,
    questionNo: '51',
    questionEn: 'Choose the correct tense: "By next week, she ______ the project."',
    questionTa: 'சரியான காலத்தைத் தேர்ந்தெடுக்கவும்: "By next week, she ______ the project."',
    optionsEn: ['will have completed', 'completes', 'is completing', 'completed'],
    optionsTa: ['will have completed', 'completes', 'is completing', 'completed'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'conceptual',
    explanationEn: 'Future Perfect tense (will have completed) is used for an action finished by a certain future time.',
    explanationTa: 'எதிர்கால நிறைவு காலம் (will have completed) ஒரு குறிப்பிட்ட எதிர்கால நேரத்தில் நிறைவடைந்த செயலுக்குப் பயன்படுகிறது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_write_words',
    year: 2022,
    questionNo: '56',
    questionEn: 'What is the correct synonym of the word "rapid"?',
    questionTa: '"rapid" என்ற வார்த்தையின் சரியான ஒத்தச்சொல் எது?',
    optionsEn: ['fast', 'slow', 'heavy', 'quiet'],
    optionsTa: ['fast', 'slow', 'heavy', 'quiet'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: '"fast" is a synonym of "rapid", meaning quick or speedy.',
    explanationTa: '"fast" என்பது "rapid" இன் ஒத்தச்சொல், வேகமான.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.english,
    subjectId: 'english',
    topicId: 'eng_read_phonics',
    year: 2019,
    questionNo: '61',
    questionEn: 'Which pair of words rhymes?',
    questionTa: 'எந்த ஜோடி வார்த்தைகள் ஒலி ஒத்தவை?',
    optionsEn: ['rain - pain', 'rain - road', 'book - look at', 'cat - dog'],
    optionsTa: ['rain - pain', 'rain - road', 'book - look at', 'cat - dog'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: '"rain" and "pain" share the same ending sound /eɪn/, so they rhyme.',
    explanationTa: '"rain" மற்றும் "pain" ஆகியவை /eɪn/ என்ற ஒரே இறுதி ஒலியைப் பகிர்ந்து ஒலி ஒத்தவை.',
  },
];

// ---------------------------------------------------------------------------
// Mathematics — Paper I (14 questions)
// ---------------------------------------------------------------------------
const mathsP1: SampleQuestionRow[] = [
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_number_concept',
    year: 2022,
    questionNo: '6',
    questionEn: 'What is the place value of the digit 5 in the number 5,432?',
    questionTa: '5,432 என்ற எண்ணில் 5 என்ற இலக்கத்தின் இடமதிப்பு என்ன?',
    optionsEn: ['5,000', '500', '50', '5'],
    optionsTa: ['5,000', '500', '50', '5'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'application',
    explanationEn: 'The digit 5 is in the thousands place, so its place value is 5 × 1000 = 5,000.',
    explanationTa: 'இலக்கம் 5 ஆயிரம் இடத்தில் உள்ளது, எனவே அதன் இடமதிப்பு 5 × 1000 = 5,000.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_addition_subtraction',
    year: 2019,
    questionNo: '10',
    questionEn: 'What is the sum of 482 and 319?',
    questionTa: '482 மற்றும் 319 ஆகியவற்றின் கூட்டுத்தொகை எவ்வளவு?',
    optionsEn: ['801', '791', '811', '701'],
    optionsTa: ['801', '791', '811', '701'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'application',
    explanationEn: '482 + 319 = 801.',
    explanationTa: '482 + 319 = 801.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_multiplication',
    year: 2022,
    questionNo: '14',
    questionEn: 'What is the product of 12 and 8?',
    questionTa: '12 மற்றும் 8 இன் பெருக்குத்தொகை எவ்வளவு?',
    optionsEn: ['96', '86', '106', '76'],
    optionsTa: ['96', '86', '106', '76'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'application',
    explanationEn: '12 × 8 = 96.',
    explanationTa: '12 × 8 = 96.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_fractions',
    year: 2019,
    questionNo: '18',
    questionEn: 'Which of the following fractions is equivalent to 1/2?',
    questionTa: 'பின்வருவனவற்றில் எந்த பின்னம் 1/2 க்குச் சமமானது?',
    optionsEn: ['2/4', '2/3', '1/4', '3/6 (also correct)'],
    optionsTa: ['2/4', '2/3', '1/4', '3/6 (also correct)'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: '2/4 simplifies to 1/2, so it is equivalent.',
    explanationTa: '2/4 எளிதாக்க 1/2 ஆகும், எனவே சமமானது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_2d_shapes',
    year: 2022,
    questionNo: '24',
    questionEn: 'How many sides does a hexagon have?',
    questionTa: 'அறுகோணத்திற்கு எத்தனை பக்கங்கள் உள்ளன?',
    optionsEn: ['6', '5', '7', '8'],
    optionsTa: ['6', '5', '7', '8'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'A hexagon is a polygon with six sides.',
    explanationTa: 'அறுகோணம் ஆறு பக்கங்களைக் கொண்ட பலகோணம்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_symmetry',
    year: 2019,
    questionNo: '28',
    questionEn: 'How many lines of symmetry does a square have?',
    questionTa: 'சதுரத்திற்கு எத்தனை சமச்சீர் கோடுகள் உள்ளன?',
    optionsEn: ['4', '2', '1', '0'],
    optionsTa: ['4', '2', '1', '0'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'A square has 4 lines of symmetry: two diagonals and the two midlines.',
    explanationTa: 'சதுரத்திற்கு 4 சமச்சீர் கோடுகள்: இரண்டு மூலைவிட்டங்கள் மற்றும் இரண்டு நடுக்கோடுகள்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_length_weight',
    year: 2022,
    questionNo: '33',
    questionEn: 'How many millimetres are there in 1 centimetre?',
    questionTa: '1 சென்டிமீட்டரில் எத்தனை மில்லிமீட்டர்கள் உள்ளன?',
    optionsEn: ['10', '100', '1000', '1'],
    optionsTa: ['10', '100', '1000', '1'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: '1 centimetre equals 10 millimetres.',
    explanationTa: '1 சென்டிமீட்டர் 10 மில்லிமீட்டருக்கு சமம்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_time',
    year: 2019,
    questionNo: '38',
    questionEn: 'How many minutes are there in 2 hours?',
    questionTa: '2 மணி நேரத்தில் எத்தனை நிமிடங்கள் உள்ளன?',
    optionsEn: ['120', '100', '60', '200'],
    optionsTa: ['120', '100', '60', '200'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'application',
    explanationEn: '2 × 60 = 120 minutes.',
    explanationTa: '2 × 60 = 120 நிமிடங்கள்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_money',
    year: 2022,
    questionNo: '43',
    questionEn: 'If a notebook costs ₹25, what is the cost of 4 notebooks?',
    questionTa: 'ஒரு குறிப்பேடு ₹25 எனில், 4 குறிப்பேடுகளின் விலை என்ன?',
    optionsEn: ['₹100', '₹80', '₹120', '₹75'],
    optionsTa: ['₹100', '₹80', '₹120', '₹75'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'application',
    explanationEn: '4 × 25 = ₹100.',
    explanationTa: '4 × 25 = ₹100.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_patterns',
    year: 2019,
    questionNo: '48',
    questionEn: 'Continue the pattern: 2, 4, 6, 8, ?',
    questionTa: 'முறையைத் தொடரவும்: 2, 4, 6, 8, ?',
    optionsEn: ['10', '9', '12', '11'],
    optionsTa: ['10', '9', '12', '11'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'application',
    explanationEn: 'The pattern adds 2 each time, so the next number is 10.',
    explanationTa: 'முறை ஒவ்வொரு முறையும் 2 ஐக் கூட்டுகிறது, எனவே அடுத்த எண் 10.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_data',
    year: 2022,
    questionNo: '53',
    questionEn: 'A graph showing data using bars is called a:',
    questionTa: 'கம்பிகளைப் பயன்படுத்தி தரவைக் காட்டும் வரைபடம் எவ்வாறு அழைக்கப்படுகிறது?',
    optionsEn: ['Bar graph', 'Pie chart', 'Line graph', 'Pictograph'],
    optionsTa: ['கம்பி வரைபடம்', 'வட்ட விளக்கப்படம்', 'கோடு வரைபடம்', 'படவரைபடம்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'A bar graph uses rectangular bars to represent data values.',
    explanationTa: 'கம்பி வரைபடம் தரவு மதிப்புகளைக் குறிக்க செவ்வக கம்பிகளைப் பயன்படுத்துகிறது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_fractions',
    year: 2019,
    questionNo: '58',
    questionEn: 'What is 3/4 expressed as a decimal?',
    questionTa: '3/4 ஐ தசமமாக வெளிப்படுத்தினால் என்ன?',
    optionsEn: ['0.75', '0.34', '0.43', '3.4'],
    optionsTa: ['0.75', '0.34', '0.43', '3.4'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'application',
    explanationEn: '3 divided by 4 equals 0.75.',
    explanationTa: '3 ஐ 4 ஆல் வகுக்க 0.75 கிடைக்கும்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_length_weight',
    year: 2022,
    questionNo: '62',
    questionEn: 'Which unit is used to measure the weight of a bag of rice?',
    questionTa: 'அரிசி மூட்டையின் எடையை அளக்க எந்த அலகு பயன்படுத்தப்படுகிறது?',
    optionsEn: ['Kilogram', 'Millilitre', 'Centimetre', 'Litre'],
    optionsTa: ['கிலோகிராம்', 'மில்லிலிட்டர்', 'சென்டிமீட்டர்', 'லிட்டர்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'Weight/mass is measured in kilograms (kg) for such items.',
    explanationTa: 'எடை/நிறை கிலோகிராமில் (kg) அளவிடப்படுகிறது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.maths,
    subjectId: 'maths',
    topicId: 'maths_number_concept',
    year: 2019,
    questionNo: '66',
    questionEn: 'What is the smallest 3-digit number?',
    questionTa: 'மிகச் சிறிய 3 இலக்க எண் எது?',
    optionsEn: ['100', '999', '101', '111'],
    optionsTa: ['100', '999', '101', '111'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: '100 is the smallest three-digit number.',
    explanationTa: '100 மிகச் சிறிய மூன்று இலக்க எண்.',
  },
];

// ---------------------------------------------------------------------------
// EVS — Paper I (14 questions)
// ---------------------------------------------------------------------------
const evsP1: SampleQuestionRow[] = [
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_plant_parts',
    year: 2022,
    questionNo: '4',
    questionEn: 'Which part of the plant is mainly responsible for absorbing water and minerals?',
    questionTa: 'தாவரத்தின் எந்தப் பகுதி முக்கியமாக தண்ணீர் மற்றும் கனிமங்களை உறிஞ்சுகிறது?',
    optionsEn: ['Roots', 'Leaves', 'Flowers', 'Fruits'],
    optionsTa: ['வேர்கள்', 'இலைகள்', 'பூக்கள்', 'பழங்கள்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'Roots absorb water and minerals from the soil.',
    explanationTa: 'வேர்கள் மண்ணிலிருந்து தண்ணீர் மற்றும் கனிமங்களை உறிஞ்சுகின்றன.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_animal_habitat',
    year: 2019,
    questionNo: '16',
    questionEn: 'A polar bear is most likely to be found in which habitat?',
    questionTa: 'பனிக்கரடி பொதுவாக எந்த வாழ்விடத்தில் காணப்படும்?',
    optionsEn: ['Arctic region', 'Desert', 'Rainforest', 'Freshwater lake'],
    optionsTa: ['ஆர்க்டிக் பகுதி', 'பாலைவனம்', 'மழைக்காடு', 'நன்னீர் ஏரி'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'Polar bears live in the cold Arctic region.',
    explanationTa: 'பனிக்கரடிகள் குளிர்ந்த ஆர்க்டிக் பகுதியில் வாழ்கின்றன.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_water',
    year: 2022,
    questionNo: '20',
    questionEn: 'Which of the following is the purest form of natural water?',
    questionTa: 'பின்வருவனவற்றில் எது மிகவும் தூய்மையான இயற்கை நீர் வடிவம்?',
    optionsEn: ['Rainwater', 'River water', 'Sea water', 'Well water'],
    optionsTa: ['மழைநீர்', 'ஆற்று நீர்', 'கடல் நீர்', 'கிணற்று நீர்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'Rainwater, formed by evaporation and condensation, is the purest natural form.',
    explanationTa: 'ஆவியாதல் மற்றும் ஒடுக்கத்தால் உருவாகும் மழைநீர் மிகத் தூய்மையான இயற்கை வடிவம்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_air',
    year: 2019,
    questionNo: '34',
    questionEn: 'Which gas in air is essential for respiration in living beings?',
    questionTa: 'உயிரினங்களின் சுவாசத்திற்கு அவசியமான காற்றில் உள்ள வாயு எது?',
    optionsEn: ['Oxygen', 'Carbon dioxide', 'Nitrogen', 'Hydrogen'],
    optionsTa: ['ஆக்சிஜன்', 'கார்பன் டை ஆக்சைடு', 'நைட்ரஜன்', 'ஹைட்ரஜன்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'Oxygen is essential for respiration in living beings.',
    explanationTa: 'உயிரினங்களின் சுவாசத்திற்கு ஆக்சிஜன் அவசியம்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_food',
    year: 2022,
    questionNo: '39',
    questionEn: 'Which nutrient is the main source of quick energy for the body?',
    questionTa: 'உடலுக்கு விரைவான சக்தியின் முக்கிய மூலம் எந்த ஊட்டச்சத்து?',
    optionsEn: ['Carbohydrates', 'Proteins', 'Vitamins', 'Minerals'],
    optionsTa: ['கார்போஹைட்ரேட்டுகள்', 'புரதங்கள்', 'வைட்டமின்கள்', 'கனிமங்கள்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'Carbohydrates provide the main quick source of energy.',
    explanationTa: 'கார்போஹைட்ரேட்டுகள் விரைவான சக்தியின் முக்கிய மூலத்தை வழங்குகின்றன.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_body',
    year: 2019,
    questionNo: '45',
    questionEn: 'Which organ pumps blood throughout the human body?',
    questionTa: 'மனித உடலில் ரத்தத்தை முழுவதும் செலுத்தும் உறுப்பு எது?',
    optionsEn: ['Heart', 'Lungs', 'Kidney', 'Liver'],
    optionsTa: ['இதயம்', 'நுரையீரல்', 'சிறுநீரகம்', 'கல்லீரல்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'The heart pumps blood throughout the body.',
    explanationTa: 'இதயம் உடல் முழுவதும் ரத்தத்தைச் செலுத்துகிறது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_health',
    year: 2022,
    questionNo: '49',
    questionEn: 'Which of the following is a hygienic practice to prevent disease?',
    questionTa: 'நோயைத் தடுக்க பின்வருவனவற்றில் எது சுகாதாரமான பழக்கம்?',
    optionsEn: ['Washing hands before meals', 'Drinking unclean water', 'Sharing towels', 'Skipping baths'],
    optionsTa: ['உணவுக்கு முன் கைகளைக் கழுவுதல்', 'சுத்தமற்ற தண்ணீர் குடித்தல்', 'துண்டைப் பகிர்தல்', 'குளிப்பதைத் தவிர்த்தல்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'Washing hands before meals removes germs and prevents disease.',
    explanationTa: 'உணவுக்கு முன் கைகளைக் கழுவுதல் கிருமிகளை நீக்கி நோயைத் தடுக்கிறது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_matter',
    year: 2019,
    questionNo: '54',
    questionEn: 'Water, ice and steam are examples of which states of matter?',
    questionTa: 'நீர், பனி மற்றும் நீராவி ஆகியவை எந்த நிலைகளின் எடுத்துக்காட்டுகள்?',
    optionsEn: ['Liquid, solid, gas', 'Solid, gas, liquid', 'Gas, liquid, solid', 'Solid, liquid, gas'],
    optionsTa: ['திரவம், திடம், வாயு', 'திடம், வாயு, திரவம்', 'வாயு, திரவம், திடம்', 'திடம், திரவம், வாயு'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'Water is liquid, ice is solid, and steam is gas.',
    explanationTa: 'நீர் திரவம், பனி திடம், நீராவி வாயு.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_energy',
    year: 2022,
    questionNo: '59',
    questionEn: 'Which energy source is renewable and obtained from the sun?',
    questionTa: 'சூரியனிலிருந்து பெறப்படும் புதுப்பிக்கத்தக்க எரிசக்தி மூலம் எது?',
    optionsEn: ['Solar energy', 'Coal', 'Petroleum', 'Natural gas'],
    optionsTa: ['சூரிய ஆற்றல்', 'நிலக்கரி', 'பெட்ரோலியம்', 'இயற்கை எரிவாயு'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'Solar energy, captured from the sun, is renewable and clean.',
    explanationTa: 'சூரியனிலிருந்து கைப்பற்றப்படும் சூரிய ஆற்றல் புதுப்பிக்கத்தக்கது, தூய்மையானது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_small_creatures',
    year: 2019,
    questionNo: '63',
    questionEn: 'Which of these is an insect?',
    questionTa: 'இவற்றில் எது பூச்சி?',
    optionsEn: ['Butterfly', 'Frog', 'Bird', 'Fish'],
    optionsTa: ['வண்ணத்துப்பூச்சி', 'தவளை', 'பறவை', 'மீன்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'A butterfly has six legs and three body parts, making it an insect.',
    explanationTa: 'வண்ணத்துப்பூச்சிக்கு ஆறு கால்கள் மற்றும் மூன்று உடல் பகுதிகள் உள்ளன, இது பூச்சியாக்குகிறது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_day_night',
    year: 2022,
    questionNo: '67',
    questionEn: 'Day and night occur on Earth due to which factor?',
    questionTa: 'பகல் மற்றும் இரவு பூமியில் எந்த காரணத்தால் நிகழ்கிறது?',
    optionsEn: ['Rotation of the Earth', 'Revolution of the Earth', 'Tilt of the axis', 'Moon\u0027s orbit'],
    optionsTa: ['பூமியின் சுழற்சி', 'பூமியின் பரிவர்த்தனை', 'அச்சின் சாய்வு', 'நிலவின் சுற்றுப்பாதை'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'The Earth\u0027s rotation on its axis causes day and night.',
    explanationTa: 'பூமியின் அச்சில் சுழற்சி பகல் மற்றும் இரவை ஏற்படுத்துகிறது.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_family_community',
    year: 2019,
    questionNo: '68',
    questionEn: 'A group of families living together and sharing common facilities is known as a:',
    questionTa: 'ஒன்றாக வாழும் மற்றும் பொதுவான வசதிகளைப் பகிர்ந்துகொள்ளும் குடும்பங்களின் குழு என அழைக்கப்படுகிறது:',
    optionsEn: ['Community', 'Individual', 'School', 'Forest'],
    optionsTa: ['சமூகம்', 'தனிநபர்', 'பள்ளி', 'காடு'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'A community is a group of families sharing common facilities and interests.',
    explanationTa: 'சமூகம் என்பது பொதுவான வசதிகளையும் நலன்களையும் பகிர்ந்துகொள்ளும் குடும்பங்களின் குழு.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_tamilnadu',
    year: 2022,
    questionNo: '69',
    questionEn: 'Which river is the longest river entirely within Tamil Nadu?',
    questionTa: 'தமிழ்நாட்டிற்குள்ளேயே முழுவதுமாக ஓடும் மிக நீளமான நதி எது?',
    optionsEn: ['Kaveri', 'Ganga', 'Yamuna', 'Sindhu'],
    optionsTa: ['காவிரி', 'கங்கை', 'யமுனை', 'சிந்து'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'The Kaveri is the major river flowing through Tamil Nadu.',
    explanationTa: 'காவிரி தமிழ்நாட்டின் முக்கிய நதியாகும்.',
  },
  {
    paper: 'PAPER_I',
    subject: SUBJECT_DISPLAY.evs,
    subjectId: 'evs',
    topicId: 'evs_india',
    year: 2019,
    questionNo: '70',
    questionEn: 'Which national animal of India is known for its protection in Project Tiger?',
    questionTa: 'புலிகள் திட்டத்தில் பாதுகாக்கப்படும் இந்தியாவின் தேசிய விலங்கு எது?',
    optionsEn: ['Tiger', 'Lion', 'Elephant', 'Deer'],
    optionsTa: ['புலி', 'சிங்கம்', 'யானை', 'மான்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'The tiger, India\u0027s national animal, is protected under Project Tiger.',
    explanationTa: 'இந்தியாவின் தேசிய விலங்கான புலி, புலிகள் திட்டத்தில் பாதுகாக்கப்படுகிறது.',
  },
];

// ---------------------------------------------------------------------------
// Maths & Science — Paper II (14 questions)
// ---------------------------------------------------------------------------
const mathsScienceP2: SampleQuestionRow[] = [
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_real_numbers',
    year: 2022,
    questionNo: '2',
    questionEn: 'Which of the following is an irrational number?',
    questionTa: 'பின்வருவனவற்றில் எது விகிதமுறா எண்?',
    optionsEn: ['√2', '4', '0.5', '22/7'],
    optionsTa: ['√2', '4', '0.5', '22/7'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'conceptual',
    explanationEn: '√2 cannot be expressed as a ratio of two integers, so it is irrational.',
    explanationTa: '√2 ஐ இரண்டு முழு எண்களின் விகிதமாக வெளிப்படுத்த முடியாது, எனவே விகிதமுறா எண்.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_algebra',
    year: 2019,
    questionNo: '12',
    questionEn: 'If x + 5 = 12, what is the value of x?',
    questionTa: 'x + 5 = 12 எனில், x இன் மதிப்பு என்ன?',
    optionsEn: ['7', '5', '17', '60'],
    optionsTa: ['7', '5', '17', '60'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'application',
    explanationEn: 'x = 12 − 5 = 7.',
    explanationTa: 'x = 12 − 5 = 7.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_lines_angles',
    year: 2022,
    questionNo: '22',
    questionEn: 'What is the measure of a right angle in degrees?',
    questionTa: 'செங்கோணத்தின் அளவு டிகிரியில் என்ன?',
    optionsEn: ['90°', '45°', '180°', '360°'],
    optionsTa: ['90°', '45°', '180°', '360°'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'A right angle measures exactly 90 degrees.',
    explanationTa: 'செங்கோணம் சரியாக 90 டிகிரி அளவிடுகிறது.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_mensuration',
    year: 2019,
    questionNo: '32',
    questionEn: 'What is the area of a rectangle with length 8 cm and width 5 cm?',
    questionTa: 'நீளம் 8 செமீ மற்றும் அகலம் 5 செமீ கொண்ட செவ்வகத்தின் பரப்பளவு என்ன?',
    optionsEn: ['40 sq cm', '13 sq cm', '45 sq cm', '80 sq cm'],
    optionsTa: ['40 சதுர செமீ', '13 சதுர செமீ', '45 சதுர செமீ', '80 சதுர செமீ'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'application',
    explanationEn: 'Area = length × width = 8 × 5 = 40 sq cm.',
    explanationTa: 'பரப்பளவு = நீளம் × அகலம் = 8 × 5 = 40 சதுர செமீ.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_matter',
    year: 2022,
    questionNo: '42',
    questionEn: 'Which state of matter has a definite shape and a definite volume?',
    questionTa: 'எந்த நிலை பொருளுக்கு உறுதியான வடிவமும் உறுதியான கன அளவும் உள்ளது?',
    optionsEn: ['Solid', 'Liquid', 'Gas', 'Plasma'],
    optionsTa: ['திடம்', 'திரவம்', 'வாயு', 'பிளாஸ்மா'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'A solid has a definite shape and a definite volume.',
    explanationTa: 'திடத்திற்கு உறுதியான வடிவமும் உறுதியான கன அளவும் உள்ளது.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_biology',
    year: 2019,
    questionNo: '5',
    questionEn: 'The powerhouse of the cell, where energy is produced, is the:',
    questionTa: 'ஆற்றல் உற்பத்தியாகும் செல்லின் சக்தி நிலையம்:',
    optionsEn: ['Mitochondria', 'Nucleus', 'Ribosome', 'Cell wall'],
    optionsTa: ['மைட்டோகாண்ட்ரியா', 'கரு', 'ரைபோசோம்', 'செல் சுவர்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'The mitochondria generate energy (ATP) for the cell.',
    explanationTa: 'மைட்டோகாண்ட்ரியா செல்லுக்கு ஆற்றலை (ATP) உருவாக்குகிறது.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_forces',
    year: 2022,
    questionNo: '15',
    questionEn: 'Which force opposes the motion of an object sliding on a surface?',
    questionTa: 'மேற்பரப்பில் சறுக்கும் பொருளின் இயக்கத்தை எதிர்க்கும் விசை எது?',
    optionsEn: ['Friction', 'Gravity', 'Magnetism', 'Upthrust'],
    optionsTa: ['உராய்வு', 'புவிஈர்ப்பு', 'காந்தவிசை', 'மேலுந்துகை'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'conceptual',
    explanationEn: 'Friction is the force that opposes sliding motion between surfaces.',
    explanationTa: 'உராய்வு என்பது மேற்பரப்புகளுக்கு இடையே சறுக்கும் இயக்கத்தை எதிர்க்கும் விசை.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_light_sound',
    year: 2019,
    questionNo: '25',
    questionEn: 'Which phenomenon explains the formation of shadows?',
    questionTa: 'நிழல்கள் உருவாவதை விளக்கும் நிகழ்வு எது?',
    optionsEn: ['Rectilinear propagation of light', 'Reflection of light', 'Refraction of light', 'Diffraction of light'],
    optionsTa: ['ஒளியின் நேர்கோட்டு பரவல்', 'ஒளியின் எதிரொளிப்பு', 'ஒளியின் விலகல்', 'ஒளியின் விளிம்பு வளைவு'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'conceptual',
    explanationEn: 'Shadows form because light travels in straight lines and cannot bend around obstacles.',
    explanationTa: 'ஒளி நேர்கோட்டில் பயணித்து தடைகளைச் சுற்றி வளைக்க முடியாததால் நிழல்கள் உருவாகின்றன.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_algebra',
    year: 2022,
    questionNo: '35',
    questionEn: 'Factorise: x² − 9',
    questionTa: 'காரணிப்படுத்துக: x² − 9',
    optionsEn: ['(x+3)(x−3)', '(x+9)(x−1)', '(x−3)(x−3)', '(x+3)(x+3)'],
    optionsTa: ['(x+3)(x−3)', '(x+9)(x−1)', '(x−3)(x−3)', '(x+3)(x+3)'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'application',
    explanationEn: 'x² − 9 is a difference of squares: (x−3)(x+3).',
    explanationTa: 'x² − 9 சதுரங்களின் வேறுபாடு: (x−3)(x+3).',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_mensuration',
    year: 2019,
    questionNo: '45',
    questionEn: 'What is the circumference of a circle with radius 7 cm? (Use π = 22/7)',
    questionTa: 'ஆரம் 7 செமீ கொண்ட வட்டத்தின் சுற்றளவு என்ன? (π = 22/7 பயன்படுத்தவும்)',
    optionsEn: ['44 cm', '22 cm', '154 cm', '14 cm'],
    optionsTa: ['44 செமீ', '22 செமீ', '154 செமீ', '14 செமீ'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'application',
    explanationEn: 'Circumference = 2πr = 2 × 22/7 × 7 = 44 cm.',
    explanationTa: 'சுற்றளவு = 2πr = 2 × 22/7 × 7 = 44 செமீ.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_biology',
    year: 2022,
    questionNo: '52',
    questionEn: 'Photosynthesis mainly occurs in which part of the plant?',
    questionTa: 'ஒளிச்சேர்க்கை முக்கியமாக தாவரத்தின் எந்தப் பகுதியில் நடைபெறுகிறது?',
    optionsEn: ['Leaf', 'Root', 'Stem only', 'Flower'],
    optionsTa: ['இலை', 'வேர்', 'தண்டு மட்டும்', 'பூ'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'Photosynthesis mainly occurs in the leaves where chlorophyll is present.',
    explanationTa: 'ஒளிச்சேர்க்கை குளோரோபில் உள்ள இலைகளில் முக்கியமாக நடைபெறுகிறது.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_forces',
    year: 2019,
    questionNo: '58',
    questionEn: 'According to Newton\u0027s first law, an object at rest will remain at rest unless:',
    questionTa: 'நியூட்டனின் முதல் விதிப்படி, ஓய்வில் உள்ள பொருள் எதுவரை ஓய்வில் இருக்கும்?',
    optionsEn: ['An external unbalanced force acts on it', 'It is observed by someone', 'Its temperature changes', 'It absorbs light'],
    optionsTa: ['வெளிப்புற சமநிலையற்ற விசை செயல்படும் வரை', 'யாரோ கவனிக்கும் வரை', 'அதன் வெப்பநிலை மாறும் வரை', 'ஒளியை உறிஞ்சும் வரை'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'Newton\u0027s first law (inertia) states an object stays at rest or uniform motion unless acted on by an external unbalanced force.',
    explanationTa: 'நியூட்டனின் முதல் விதி (யோர்வு), வெளிப்புற சமநிலையற்ற விசை செயல்படாத வரை பொருள் ஓய்விலோ சீரான இயக்கத்திலோ இருக்கும்.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_real_numbers',
    year: 2022,
    questionNo: '61',
    questionEn: 'How many prime numbers are there between 1 and 10?',
    questionTa: '1 மற்றும் 10 க்கு இடையில் எத்தனை பகா எண்கள் உள்ளன?',
    optionsEn: ['4', '3', '5', '6'],
    optionsTa: ['4', '3', '5', '6'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'The primes between 1 and 10 are 2, 3, 5, 7 — four primes.',
    explanationTa: '1 மற்றும் 10 க்கு இடையிலான பகா எண்கள் 2, 3, 5, 7 — நான்கு.',
  },
  {
    paper: 'PAPER_II_MATH_SCI',
    subject: SUBJECT_DISPLAY.maths_science,
    subjectId: 'maths_science',
    topicId: 'ms_light_sound',
    year: 2019,
    questionNo: '65',
    questionEn: 'The speed of sound is greatest in which medium?',
    questionTa: 'எந்த ஊடகத்தில் ஒலியின் வேகம் அதிகம்?',
    optionsEn: ['Solids', 'Liquids', 'Gases', 'Vacuum'],
    optionsTa: ['திடப்பொருட்கள்', 'திரவங்கள்', 'வாயுக்கள்', 'வெற்றிடம்'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'conceptual',
    explanationEn: 'Sound travels fastest in solids where particles are tightly packed.',
    explanationTa: 'துகள்கள் நெருக்கமாக அமைந்த திடப்பொருட்களில் ஒலி வேகமாகப் பயணிக்கிறது.',
  },
];

// ---------------------------------------------------------------------------
// Social Science — Paper II (14 questions)
// ---------------------------------------------------------------------------
const socialScienceP2: SampleQuestionRow[] = [
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_ancient_india',
    year: 2022,
    questionNo: '3',
    questionEn: 'Which ancient Indian law-giver compiled the "Arthashastra" discussing statecraft and economy?',
    questionTa: 'அரசியல் மற்றும் பொருளாதாரம் குறித்த "அர்த்தசாஸ்திரம்" தொகுத்த பண்டைய இந்திய சட்டமைப்பாளர் யார்?',
    optionsEn: ['Kautilya (Chanakya)', 'Ashoka', 'Akbar', 'Harsha'],
    optionsTa: ['கௌடில்யர் (சாணக்கியர்)', 'அசோகர்', 'அக்பர்', 'ஹர்ஷர்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'Kautilya (Chanakya) authored the Arthashastra on statecraft and economy.',
    explanationTa: 'கௌடில்யர் (சாணக்கியர்) அரசியல் மற்றும் பொருளாதாரம் குறித்த அர்த்தசாஸ்திரத்தை எழுதினார்.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_physio_india',
    year: 2019,
    questionNo: '11',
    questionEn: 'The Himalayas are classified as which type of mountain?',
    questionTa: 'இமயமலை எந்த வகை மலையாக வகைப்படுத்தப்படுகிறது?',
    optionsEn: ['Fold mountains', 'Block mountains', 'Volcanic mountains', 'Plateau mountains'],
    optionsTa: ['மடிப்பு மலைகள்', 'தொகுதி மலைகள்', 'எரிமலை மலைகள்', 'பீடபூமி மலைகள்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'The Himalayas are young fold mountains formed by tectonic plate collision.',
    explanationTa: 'இமயமலை தட்டு மோதலால் உருவான இளம் மடிப்பு மலைகள்.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_medieval_modern',
    year: 2022,
    questionNo: '18',
    questionEn: 'The first Battle of Panipat (1526) marked the beginning of which empire?',
    questionTa: 'முதல் பானிபட் போர் (1526) எந்த பேரரசின் தொடக்கத்தைக் குறித்தது?',
    optionsEn: ['Mughal Empire', 'Maratha Empire', 'British Raj', 'Vijayanagara'],
    optionsTa: ['முகலாய பேரரசு', 'மராத்தா பேரரசு', 'பிரிட்டிஷ் ஆட்சி', 'விஜயநகரம்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'Babur\u0027s victory at Panipat in 1526 founded the Mughal Empire.',
    explanationTa: '1526 இல் பானிபட்டில் பாபரின் வெற்றி முகலாய பேரரசை நிறுவியது.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_democracy',
    year: 2019,
    questionNo: '26',
    questionEn: '"Government of the people, by the people, for the people" defines which concept?',
    questionTa: '"மக்களால், மக்களுக்காக, மக்களின் அரசு" எந்த கருத்தை வரையறுக்கிறது?',
    optionsEn: ['Democracy', 'Monarchy', 'Dictatorship', 'Theocracy'],
    optionsTa: ['ஜனநாயகம்', 'முடியாட்சி', 'சர்வாதிகாரம்', 'இறையாட்சி'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'Abraham Lincoln\u0027s famous phrase defines democracy.',
    explanationTa: 'ஆபிரகாம் லிங்கனின் புகழ்பெற்ற சொற்றொடர் ஜனநாயகத்தை வரையறுக்கிறது.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_tamilnadu_history',
    year: 2022,
    questionNo: '31',
    questionEn: 'Which Sangam age Tamil kingdom was known for the port city of Musiri (Muziris)?',
    questionTa: 'முசிறி துறைமுக நகருக்கு பெயர் பெற்ற சங்க கால தமிழ் அரசு எது?',
    optionsEn: ['Chera', 'Chola', 'Pandya', 'Pallava'],
    optionsTa: ['சேரர்', 'சோழர்', 'பாண்டியர்', 'பல்லவர்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'The Cheras ruled the region west of the Western Ghats including the Musiri (Muziris) port.',
    explanationTa: 'சேரர்கள் மேற்கு தொடர்ச்சி மலைக்கு மேற்கே முசிறி துறைமுகம் உட்பட பகுதியை ஆண்டனர்.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_indian_economy',
    year: 2019,
    questionNo: '36',
    questionEn: 'The primary sector of the Indian economy mainly involves:',
    questionTa: 'இந்திய பொருளாதாரத்தின் முதன்மைத் துறை முக்கியமாக ஈடுபடுவது:',
    optionsEn: ['Agriculture and raw material extraction', 'Manufacturing goods', 'Banking services', 'Information technology'],
    optionsTa: ['விவசாயம் மற்றும் மூலப்பொருள் பிரித்தெடுத்தல்', 'பொருட்கள் உற்பத்தி', 'வங்கி சேவைகள்', 'தகவல் தொழில்நுட்பம்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'conceptual',
    explanationEn: 'Agriculture and raw material extraction form the primary sector.',
    explanationTa: 'விவசாயம் மற்றும் மூலப்பொருள் பிரித்தெடுத்தல் முதன்மைத் துறையை உருவாக்குகிறது.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_local_govt',
    year: 2022,
    questionNo: '40',
    questionEn: 'Which constitutional amendment gave constitutional status to Panchayati Raj institutions?',
    questionTa: 'பஞ்சாயத்து ராஜ் நிறுவனங்களுக்கு அரசியலமைப்பு அந்தஸ்து அளித்த திருத்தம் எது?',
    optionsEn: ['73rd Amendment', '42nd Amendment', '44th Amendment', '86th Amendment'],
    optionsTa: ['73வது திருத்தம்', '42வது திருத்தம்', '44வது திருத்தம்', '86வது திருத்தம்'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'factual',
    explanationEn: 'The 73rd Constitutional Amendment (1992) gave constitutional status to Panchayati Raj.',
    explanationTa: '73வது அரசியலமைப்பு திருத்தம் (1992) பஞ்சாயத்து ராஜுக்கு அரசியலமைப்பு அந்தஸ்து அளித்தது.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_ancient_india',
    year: 2019,
    questionNo: '44',
    questionEn: 'Which Harappan site is known as the "Manchester of the ancient world" for cotton trade?',
    questionTa: 'பருத்தி வர்த்தகத்திற்கு "பண்டைய உலகின் மான்செஸ்டர்" என அழைக்கப்படும் ஹரப்பன் தளம் எது?',
    optionsEn: ['Lothal', 'Mohenjo-daro', 'Harappa', 'Kalibangan'],
    optionsTa: ['லோதல்', 'மொஹஞ்சதாரோ', 'ஹரப்பா', 'காளிபங்கன்'],
    correctIndex: 0,
    difficulty: 'hard',
    questionType: 'factual',
    explanationEn: 'Lothal, a Harappan port, was renowned for its cotton trade and dockyard.',
    explanationTa: 'லோதல், ஒரு ஹரப்பன் துறைமுகம், பருத்தி வர்த்தகம் மற்றும் கப்பல்துறைக்கு புகழ்பெற்றது.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_medieval_modern',
    year: 2022,
    questionNo: '48',
    questionEn: 'The Revolt of 1857 is also known as:',
    questionTa: '1857 இன் கிளர்ச்சி என்ன அழைக்கப்படுகிறது?',
    optionsEn: ['India\u0027s First War of Independence', 'The Partition of Bengal', 'The Salt March', 'The Quit India Movement'],
    optionsTa: ['இந்தியாவின் முதல் சுதந்திரப் போர்', 'வங்க பிரிவினை', 'உப்பு சத்தியாகிரகம்', 'வெள்ளையனே வெளியேறு இயக்கம்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'The Revolt of 1857 is often called India\u0027s First War of Independence.',
    explanationTa: '1857 இன் கிளர்ச்சி இந்தியாவின் முதல் சுதந்திரப் போர் என அழைக்கப்படுகிறது.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_tamilnadu_history',
    year: 2019,
    questionNo: '53',
    questionEn: 'Which Chola ruler built the Brihadeeswarar Temple at Thanjavur?',
    questionTa: 'தஞ்சையில் பிரகதீஸ்வரர் கோவிலை கட்டிய சோழ மன்னன் யார்?',
    optionsEn: ['Raja Raja Chola I', 'Rajendra Chola I', 'Karikala Chola', 'Kulothunga Chola'],
    optionsTa: ['முதலாம் ராஜராஜ சோழன்', 'முதலாம் ராஜேந்திர சோழன்', 'கரிகால சோழன்', 'குலோத்துங்க சோழன்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'Raja Raja Chola I built the Brihadeeswarar Temple at Thanjavur (c. 1010 CE).',
    explanationTa: 'முதலாம் ராஜராஜ சோழன் தஞ்சை பிரகதீஸ்வரர் கோவிலை கட்டினார் (கி.பி. 1010).',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_physio_india',
    year: 2022,
    questionNo: '57',
    questionEn: 'The Deccan Plateau lies between which two ranges in India?',
    questionTa: 'தக்காண பீடபூமி இந்தியாவில் எந்த இரண்டு மலைத்தொடர்களுக்கு இடையில் உள்ளது?',
    optionsEn: ['Western and Eastern Ghats', 'Himalayas and Aravalli', 'Vindhya and Satpura', 'Nilgiri and Annamalai'],
    optionsTa: ['மேற்கு மற்றும் கிழக்கு தொடர்ச்சி மலைகள்', 'இமயம் மற்றும் அரவள்ளி', 'விந்தியா மற்றும் சத்புரா', 'நீலகிரி மற்றும் அண்ணாமலை'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'The Deccan Plateau is bounded by the Western and Eastern Ghats.',
    explanationTa: 'தக்காண பீடபூமி மேற்கு மற்றும் கிழக்கு தொடர்ச்சி மலைகளால் எல்லைப்படுத்தப்படுகிறது.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_democracy',
    year: 2019,
    questionNo: '60',
    questionEn: 'The fundamental right that allows citizens to move freely throughout the country is the right to:',
    questionTa: 'குடிமக்கள் நாடு முழுவதும் சுதந்திரமாக செல்ல அனுமதிக்கும் அடிப்படை உரிமை எது?',
    optionsEn: ['Freedom of movement', 'Freedom of speech', 'Freedom of religion', 'Right to property'],
    optionsTa: ['நடமாடும் சுதந்திரம்', 'பேச்சு சுதந்திரம்', 'மத சுதந்திரம்', 'சொத்து உரிமை'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'Freedom of movement is a fundamental right under Article 19 of the Constitution.',
    explanationTa: 'நடமாடும் சுதந்திரம் அரசியலமைப்பின் சரத்து 19-இன் கீழ் அடிப்படை உரிமை.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_indian_economy',
    year: 2022,
    questionNo: '63',
    questionEn: 'The 1991 economic reforms in India are most closely associated with the policy of:',
    questionTa: 'இந்தியாவில் 1991 பொருளாதார சீர்திருத்தங்கள் எந்த கொள்கையுடன் மிக நெருக்கமாக தொடர்புடையவை?',
    optionsEn: ['Liberalisation and privatisation', 'Total nationalisation', 'Import substitution', 'Closing foreign trade'],
    optionsTa: ['தாராளமயமாக்கல் மற்றும் தனியார்மயமாக்கல்', 'முழு தேசியமயமாக்கல்', 'இறக்குமதி மாற்றீடு', 'வெளிநாட்டு வர்த்தகம் மூடுதல்'],
    correctIndex: 0,
    difficulty: 'medium',
    questionType: 'factual',
    explanationEn: 'The 1991 reforms introduced liberalisation, privatisation and globalisation (LPG).',
    explanationTa: '1991 சீர்திருத்தங்கள் தாராளமயமாக்கல், தனியார்மயமாக்கல் மற்றும் உலகமயமாக்கலை (LPG) அறிமுகப்படுத்தியது.',
  },
  {
    paper: 'PAPER_II_SOC_SCI',
    subject: SUBJECT_DISPLAY.social_science,
    subjectId: 'social_science',
    topicId: 'ss_local_govt',
    year: 2019,
    questionNo: '66',
    questionEn: 'The head of a Panchayat at the village level is called the:',
    questionTa: 'கிராம அளவில் பஞ்சாயத்தின் தலைவர் என அழைக்கப்படுகிறார்:',
    optionsEn: ['Sarpanch', 'Mayor', 'Collector', 'Minister'],
    optionsTa: ['சர்பஞ்ச்', 'மேயர்', 'கலெக்டர்', 'அமைச்சர்'],
    correctIndex: 0,
    difficulty: 'easy',
    questionType: 'factual',
    explanationEn: 'The Sarpanch heads the village-level gram panchayat.',
    explanationTa: 'சர்பஞ்ச் கிராம அளவிலான கிராம பஞ்சாயத்தை வழிநடத்துகிறார்.',
  },
];

// ---------------------------------------------------------------------------
// Assemble all 100 sample questions
// ---------------------------------------------------------------------------
export const SAMPLE_QUESTIONS: SampleQuestionRow[] = [
  ...cdpP1,
  ...cdpP2,
  ...tamilP1,
  ...englishP1,
  ...mathsP1,
  ...evsP1,
  ...mathsScienceP2,
  ...socialScienceP2,
];
